Feat/card search - added search page
cardbox/frontend pull request #26
Opened 2021-06-06 15:56 UTC by OlegBrony

- [x] This PullRequest implements new feature, fix bug, or some other changes
  - [ ] If PR is not ready mark it as Draft
  - [x] All commits in this PR should be created by `yarn commit` by [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/)

2021-06-06 17:14 UTC, sergeysova requested changes

2021-06-06 17:14 UTC, sergeysova commented on src/entities/user/organisms/user-preview.tsx
> +            {user.cardsCount} card{getSEnd(user.cardsCount)}
```suggestion
            {user.cardsCount}{plural(user.cardsCount, “card”, “cards”)
```

2021-06-06 17:14 UTC, sergeysova commented on src/features/search-bar/index.ts
> +import * as model from './models';
```suggestion
export * as model from './models';
```

2021-06-06 17:14 UTC, sergeysova commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
Чет это костылями пахнет. Это ж просто роутинг пути. Квери к роутам не относятся

2021-06-06 17:24 UTC, OlegBrony commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
Ну мне хотелось, чтоб в использовании было просто .search(query), а не `.search()?query=${query}`

2021-06-06 17:26 UTC, sergeysova commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
Думаю стоит утащить это на уровень historyPush

2021-06-06 17:34 UTC, OlegBrony commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
Покажешь?

2021-06-06 21:18 UTC, OlegBrony commented on src/features/search-bar/index.ts
> +import * as model from './models';
я был уверен, что тс ругался...

2021-06-06 21:20 UTC, OlegBrony commented on src/features/search-bar/index.ts
> +import * as model from './models';
вебпак ругается. 
![image](https://user-images.githubusercontent.com/19880334/120940461-17634b00-c726-11eb-8656-6220f56bd187.png)

2021-06-06 21:25 UTC, OlegBrony commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
![image](https://user-images.githubusercontent.com/19880334/120940594-bee07d80-c726-11eb-959c-cf52a4c60e9b.png)
![image](https://user-images.githubusercontent.com/19880334/120940600-c4d65e80-c726-11eb-9545-6851d0edb60d.png)
мне второй вариант больше нравится.

2021-06-06 21:49 UTC, OlegBrony commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
Хм... А разве не относится? Без квери не имеет же смысла. В данном случае как минимум.

2021-06-16 21:55 UTC, martis-git commented on src/features/search-bar/index.ts
> +import * as model from './models';
https://babeljs.io/docs/en/babel-plugin-proposal-export-namespace-from ?

2021-06-16 22:41 UTC, martis-git requested changes
@OlegBrony Сорямба Олег))

Старался как мог не придираться, но глаз цеплялся...

![image](https://user-images.githubusercontent.com/42924400/122303924-09bf7980-cf0d-11eb-8428-0bc3e5d43187.png)

2021-06-16 22:41 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
Имхо, выглядит всрато так хуки реактовские юзать)

Да, я вижу, что и @sergeysova их 9 месяцев назад юзал, но думаю - надо бы обсудить момент

2021-06-16 22:41 UTC, martis-git commented on src/lib/use-query.ts
> +}
Мб набрасываю, но если мы говорим про "либу", а не "очередную свалку хелперов" то и название нужно соответствующее)

А то назвал одноименно хуку, и уже либа слишком "узкоспециализированная" выходит

2021-06-16 22:41 UTC, martis-git commented on src/lib/use-query.ts
> +}
А вообще камон изборетать велосипеды, готе использовать проверенное добро))
(можем похоливарить - но эта штука меня по работе и пет проектах кучу раз спасала)

Сам кучу велосипедов написал для query-params, но эта штука - пушка *(правда под SSR не тестил, но думаю не должно быть проблем)*
https://github.com/pbeshai/use-query-params

2021-06-16 22:41 UTC, martis-git commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
Я ща конечн не угадаю ,как именно хотел Сергей написать

Но тут рили надо разграничивать:
- Есть роут и его базовые параметры (например `/card/:cardId`)
- А есть query-параметры (которые при желании могут вообще от страницы к странице таскаться)

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/model.ts
> +  cards_count: number;
Ммм, я бы не юзал snake_case без повода

*(ладно, когда приходит с бэка, и это проблематично нормализовать - но тут же клиент и все в нашей власти)*

2021-06-16 22:41 UTC, martis-git commented on src/features/search-bar/index.ts
> +export { model };
Я бы уже начал потихоньку юзать последнюю версию фиче слайсов ~~(а кардбоксы уже не спасутся от этого :D)~~

Поэтому Public API должен в том числе разруливать коллизии

https://feature-sliced.design/docs/concepts/public-api/#3-%D0%B8%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B8%D1%80%D1%83%D0%B5%D0%BC%D0%BE%D1%81%D1%82%D1%8C

![image](https://user-images.githubusercontent.com/42924400/122300889-a0d60280-cf08-11eb-9e53-0954197800a7.png)

2021-06-16 22:41 UTC, martis-git commented on src/ui/templates/index.ts
> +export { CardContainer } from './card-container';
Показалось.... 😄

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +);
Прям просится декомпозиция по фичам / сущностям

(или пока хотя бы в отдельные файлы в странице - но потом тоже поправить придется)

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +}
Снова посягаю на устои)

А это уже принятая конвенция - юзать интерфейсы для пропсов?

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +}
Они же не гибкие прост нифига относительно типов

Да и интерфейсы это больше про ООПшное применение

2021-06-16 22:41 UTC, martis-git commented on src/lib/plural.ts
> +}
https://www.npmjs.com/package/plural-ru ? (или аналоги, но для en)

2021-06-16 22:41 UTC, martis-git commented on src/lib/plural.ts
> +}
Но для англа мб и не критично пока

2021-06-16 22:41 UTC, martis-git commented on src/entities/user/organisms/user-preview.tsx
> +import { plural } from '../../../lib/plural';
Я бы юзал относительные импорты тольк для внутренних ресурсов

А для ресурсов из других слоев - уже абсолютные (или ч-з альяс "@cardbox" который тут прилюбился так понимаю)

2021-06-16 22:41 UTC, martis-git commented on src/entities/user/organisms/user-preview.tsx
> +import { plural } from '../../../lib/plural';
А то путанница жесткая возникает - что внутренний ресурс модуля, а что внешний

2021-06-16 22:41 UTC, martis-git commented on src/entities/user/organisms/user-preview.tsx
> +import { plural } from '../../../lib/plural';
Но можем похоливарить))

2021-06-16 22:41 UTC, martis-git commented on src/entities/user/types.ts
> +}
Оооооо, мой любимый холивар)))

Имхо, префиксы для типов не нужны - т.к. компиляторы и так умеют различать типы и сам код

А если идет жесткое совпадение, мешающее разработке и восприятию - это уже проблема нейминга (у нас на работе старой просто один тип оч любил везде приставлять префиксы "I" и "T" - код превращался в УГ)

2021-06-16 22:41 UTC, martis-git commented on src/entities/user/types.ts
> +}
Но офк - можем пообсуждать еще)

2021-06-16 22:41 UTC, martis-git commented on src/entities/user/types.ts
> +}
У меня где-то ссылки даже припасены были вродь на статьи хорошие

2021-06-16 22:41 UTC, martis-git commented on package.json
> -    "patronum": "^0.106.0",
ХРенасе, впервые такую минорную версию вижу)))

У @sergeysova  крепкие нервы прям

2021-06-16 22:41 UTC, martis-git commented on src/features/search-bar/models/index.ts
> +type ChangeEv = ChangeEvent<HTMLInputElement>;
1. Не вижу смысла сокращать название типа
2. Лучше импортить тип отдельным импортом (import type или динамическим, но не напрямую как модуль)
3. Если такая штука нужна, то лучше ее в глобальные типы занести и задеклейрить, чтобы по всей приложухе можно было юзать (в раззл хз каК, но в CRA это обычно react-app-env.d.ts)

2021-06-16 22:41 UTC, martis-git commented on src/features/search-bar/models/index.ts
> +});
Если поправишь роут кста, то сразу минус зависимость от уровня страниц

> Как сигнал от фиче слайсов

2021-06-16 22:41 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +          <Link to={paths.home()}>
Я бы пропсом передавал

И зависимость от слоя страниц уйдет

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +);
Меня жесть как корежит такое использование хуков

Даж если это работает для эффектора, то имхо - общих конвенций по реакту же надо придерживаться....

Но можем обсудить офк, мб я чего-то не учитываю

2021-06-16 22:41 UTC, martis-git commented on src/features/search-bar/molecules/search.tsx
> +      placeholder="Search placeholder"
Я пока не совсем смотрел распределение по задачам

Но я бы еще добавил обработку кейсов при поиске:
- [ ] Строка, для которой должна выдаваться пустая выдача (заглушка "ничего не найдено" или проч)
- [ ] Пустая строка - должен показываться тултип или должны отображаться все результаты сразу как в обычном списке
- [ ] (В идеале) Автокомплит, который бы еще вел к отдельной карточке (в woly-ui уж должен быть такой, если давний UIKit рили)

Ну и зависит многое от дизайна - как эти случаи там обыгрываются

Возможно зря набрасываю, просто это первые "цепляющие" штуки, которые при использовании режут UX

2021-06-16 22:41 UTC, martis-git commented on src/features/search-bar/molecules/search.tsx
> +      placeholder="Search placeholder"
Плюс фокусировка инпута не работает - что тож не оч
(да и наверн в UIKit должен быть компонент инпута, не?)

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/model.ts
> +);
Некритично, но я бы отдельно хранил эффекты, стор и события

Но если это одна из конвенций эффектора хранить все в куче - то оке)

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/model.ts
> +};
Имхо, фикстуры если и вводим временно (вместо API), то надо и хранить их в соответствующем модуле

Это точно не должно определяться для какой-то страницы / юзера , а скорее про `shared/api` уровень

И абсолютно точно - это не должно лежать в модели))

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/model.ts
> +}
1. Выглядит как геттер из lib-сегмента
2. Переименовать бы функцию

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/model.ts
> +);
А можешь раскрыть - зачем тут маппинг такой? Разве это не должно на UI-уровне определяться, как данные отображать? (сужу по названию сугубо)

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +import { useSearchQuery } from '@cardbox/features/search-bar';
Эххх, как не хватает сортировки импортов))
Но потом добавлю сам как руки дойдут

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +  }, [history, searchQuery]);
А это прям юзкейс такой? Имхо, не оч редиректить напрямую, если "не дай боже будет пустая строка"

Лучше отдельно проработать этот кейс со стороны взаимодействия пользователя

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
Я бы кста такое вынес на уровне модели (selectors.ts и events.ts соответственно)

Учитывая, что это SSR и нужен useEvent для эффектора - то можно в events.ts прям хук экспортить с событиями (но тут @sergeysova поправь - возможно я щас предлагаю костыли ради удобства внедрить)

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +        <p>Loading...</p>
А шо не спиннер?)

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +    return (
Некритично, но лучше бы просто `isLoading`

~~Так можно и до `thereIsShouldBeDisplayedLoadingSnippet` дойти :D~~

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/page.tsx
> +        <UserRes />
Любишь сокращения я смотрю?)

2021-06-16 22:41 UTC, martis-git commented on src/pages/search/model.ts
> +        2000,
вОТ ВООБЩЕ НЕКРИТИЧНО, но мб Math.random?)

(чтобы не всегда под 2 сек надо было ждать)

2021-06-16 22:41 UTC, martis-git commented on src/entities/user/types.ts
> +  cardsCount: number;
А здесь уже без snake_case кек)

2021-06-16 22:41 UTC, martis-git commented on src/entities/user/index.ts
> +export { UserPreviewList } from './organisms';
Задолбаешься же так постоянно прописывать каждый компонент?

Имхо, пускай более низкоуровневый Public API (т.е. `user/organisms` в данном случае) решает что должно экспортиться, а более высокоуровневый - не должен так сильно уже запариваться (т.е. если ты в `user/index.ts` сделаешь просто `export * from './organisms';` то никак же от этого анти-хрупкость не пострадает)

2021-06-16 23:13 UTC, martis-git commented
Плюс я бы более осмысленное описание изменений делал

И тебе проще рефлексировать "А не задел ли я что-то лишнее по задаче?" и ревьюверу проще понять, что тут происходит
(и тебя меньше вопросами будет заваливать)


![image](https://user-images.githubusercontent.com/42924400/122306700-9b30ea80-cf11-11eb-9507-715433675984.png)

2021-06-17 06:53 UTC, OlegBrony commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
А в чём нельзя? Законом не запрещено.

2021-06-17 06:55 UTC, OlegBrony commented on src/pages/search/model.ts
> +  cards_count: number;
Это контракт.

2021-06-17 06:56 UTC, OlegBrony commented on src/entities/user/types.ts
> +  cardsCount: number;
Это не контракт.

2021-06-17 06:57 UTC, martis-git commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
Ну тип хуки это история про то, что "ты в начале компонента вызвал какую-то логику, возможно получил данные - а потом с ними дальше оборудуешь"

И в принципе даж примерно поонимаю почему это работает

Но юзать хуки прям при передаче пропсов... Ну эт костыльно оч))

Потом у тебя компонент внезапно начнет "условно" рендериться , или в цикле - и хук перестанет работать внезапно

Не надо с хуками так играться))

https://reactjs.org/docs/hooks-rules.html (где-то в правилах хуков точно было тож написано - что из-за своей специфики реализации, их лучше вызывать в начале фукнции, когда нет еще ветвлений и циклов)

2021-06-17 06:58 UTC, martis-git commented on src/pages/search/model.ts
> +  cards_count: number;
???

2021-06-17 06:58 UTC, martis-git commented on src/entities/user/types.ts
> +  cardsCount: number;
???

2021-06-17 06:58 UTC, martis-git commented on src/pages/search/model.ts
> +  cards_count: number;
Тыж сам определяешь логику. Без Бэкенда еще даж

2021-06-18 08:34 UTC, OlegBrony commented on src/features/search-bar/index.ts
> +import * as model from './models';
wow, it was that easy?

2021-06-18 08:38 UTC, OlegBrony commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
честно, мало понял что ты имел в виду... я хочу иметь в роутах удобный апи, чтоб я просто написать routes.some() и всё работало.

2021-06-18 08:39 UTC, OlegBrony commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
да почему костыли если компонент прост как пробка?

2021-06-18 08:40 UTC, OlegBrony commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
предложи лучше.

2021-06-18 09:05 UTC, OlegBrony commented on src/lib/use-query.ts
> +}
окей, заменю. просто всегда с доки роутера брал.

2021-06-18 09:05 UTC, OlegBrony commented on src/pages/search/model.ts
> +  cards_count: number;
ну это то, что теоритически с бека приходит.

2021-06-18 09:06 UTC, OlegBrony commented on src/pages/search/model.ts
> +        2000,
сократил до 1.

2021-06-18 09:06 UTC, OlegBrony commented on src/entities/user/types.ts
> +  cardsCount: number;
что?

2021-06-18 09:55 UTC, OlegBrony commented on src/pages/search/page.tsx
> +}
на проекте интерфейсы. я спрашивал как-то Сергей почему, не помню, что он ответил)

2021-06-18 09:57 UTC, OlegBrony commented on src/lib/plural.ts
> +}
хз... добавить? https://www.npmjs.com/package/pluralize

2021-06-18 09:58 UTC, OlegBrony commented on src/entities/user/organisms/user-preview.tsx
> +import { plural } from '../../../lib/plural';
единственное, что мне не нравится в алиасах - моя иде в них не умеет 😡

2021-06-18 10:01 UTC, OlegBrony commented on src/entities/user/types.ts
> +}
что ты предлагаешь? назвать компонент UserPreviewComponent?

2021-06-18 10:03 UTC, OlegBrony commented on src/features/search-bar/models/index.ts
> +});
поясни.

2021-06-18 10:06 UTC, OlegBrony commented on src/pages/search/model.ts
> +};
ну я добавил с мыслью это удалить через время.

2021-06-18 10:07 UTC, OlegBrony commented on src/pages/search/model.ts
> +);
почему не на слое данных, которые нужны UI?

2021-06-18 10:08 UTC, OlegBrony commented on src/pages/search/page.tsx
> +import { useSearchQuery } from '@cardbox/features/search-bar';
уже посортированы.

2021-06-18 10:08 UTC, OlegBrony commented on src/pages/search/page.tsx
> +  }, [history, searchQuery]);
как ты это видишь?

2021-06-18 10:09 UTC, OlegBrony commented on src/pages/search/page.tsx
> +        <p>Loading...</p>
out of the scope)

2021-06-18 19:57 UTC, martis-git commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
Ну вот тип я примерно могу представить, почему это работает
Но так не принято писать)

У тебя хук, это ~ ЖЦ методы из классовых компонентов

Т.е. ты их непосредственно до рендера объявляешь и используешь

Не говоря уже про то, что у тебя обычно разметка должна быть простой, куда чисто данные пропихиваются

@sergeysova @risenforces @antonmazhuto Поправьте если что, я мб каких-то конвенций эффектора не знаю, но выглядит дичево так хуки юзать :(

2021-06-18 19:58 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
Ой да, сорь)
Имею в виду, что лучше напрямую импортить нужные хуки, а не через дот-нотацию доставить как свойства

(вот на 17 реакте вообще импортить реакт отдельно не надо - и придется из-за этого везде оставлять импорт всего скоупа реакта, вместо конкретных хуков)

Крч возможно "из-под капота" это выглядит примерно одинаково с отдельными импортами хуков

Но тыж хуки эффектора так не юзаешь, к примеру)

Это вродь в целом не оч практика так делать, я если статью найду - кину

Но можем пообсуждать (@risenforces @sergeysova @antonmazhuto делитесь мнениями тож)

2021-06-18 20:00 UTC, martis-git commented on src/lib/use-query.ts
> +}
@sergeysova глянь либу на всякий
Вродь должно норм для SSR работать, но именно для него не чекал

2021-06-18 20:06 UTC, martis-git commented on src/pages/search/model.ts
> +  cards_count: number;
Ну тут тогда два варика:
1. **Поговорить с бэком, чтобы нормальная сериализация к camelCase фигачилась**
 (т.к. потенциально мыж не только для веба, но и мобилок можем делать) - @Drevoed к тебе так понимаю

2. **Либо написать нормализацию на уровне `shared/api` на клиенте** 
Т.к. snake_case в JS ну не юзается прост)))
Плохой тон, обычно во всех конфигах линтеров это правило даж есть

> Но самим себе проблемы создавать не оч)
>
> Тебе же если будет с бэка приходить `"Cards-Count"` - ты ж не будешь прям так в коде юзать, согласись))

2021-06-18 20:09 UTC, martis-git commented on src/pages/search/page.tsx
> +}
Ща уточним в чате))

2021-06-18 20:11 UTC, martis-git commented on src/lib/plural.ts
> +}
Ну лан, соглашусь - пока оверхед, т.к. русского нет))

2021-06-18 20:13 UTC, martis-git commented on src/entities/user/organisms/user-preview.tsx
> +import { plural } from '../../../lib/plural';
Ну в принципе, если пока прям усложнения сильные (т.е. не просто "Автоимпорты не работают", а прям если автокомлит даж не работает) - то можно оставить и как есть

2021-06-18 20:15 UTC, martis-git commented on src/entities/user/organisms/user-preview.tsx
> +import { plural } from '../../../lib/plural';
@sergeysova что скажешь насчет `baseUrl: "./src"` ?

Чтобы не надо было каждый раз альяс кастовать для доступа к базовым слоям в src

(а если упаси боже понадобится что-то вне src в коде - то можно доп альясы все равно вродь прикрутить)

2021-06-18 20:32 UTC, martis-git commented on src/entities/user/types.ts
> +}
Предлагаю не кастовать "I" для интерфейсов (и "T" для типов) в TypeScript

Тыж когда пропсы пишешь - не пишешь "ISomeComponentProps"

Вот одна из статей, которую нашел - но есть еще, если поискать
https://medium.com/@jonyeezs/hey-typescript-wheres-my-i-prefixed-interface-cd70efa10bd1

2021-06-18 20:32 UTC, martis-git commented on src/entities/user/types.ts
> +}
`TLDR`: Если из-за префикса нельзя понять про тип/интерфейс или код мы говорим - то значит проблема в самом нейминге, а не "отсутсвии префикса"

2021-06-18 20:33 UTC, martis-git commented on src/features/search-bar/models/index.ts
> +});
Ну тип к тому, что [у тебя не на уровне `pages/paths` должны query-параметры определяться, а на уровне страницы](https://github.com/cardbox/frontend/pull/26#discussion_r653087002)

2021-06-18 20:34 UTC, martis-git commented on src/pages/search/model.ts
> +};
Ну лан, учитывая сегодняшнее распределение задач -сам поправлю уже если что)

2021-06-18 20:35 UTC, martis-git commented on src/pages/search/model.ts
> +);
Ну тип да, грань тонкая

Но по идее вся обработка данных, которая нужна для UI отображения - должна либо в селекторах юзать (а не сторе отдельном), либо прям в UI, если логика тривиальна

2021-06-18 20:37 UTC, martis-git commented on src/pages/search/model.ts
> +);
Вот как пример из todo-app для feature-sliced:

![image](https://user-images.githubusercontent.com/42924400/122613826-2931e000-d08e-11eb-83ea-18e70e8a4312.png)

2021-06-18 20:38 UTC, martis-git commented on src/pages/search/page.tsx
> +import { useSearchQuery } from '@cardbox/features/search-bar';
Ну тип у тебя внешняя зависимость (react-router) идет после внутренней))

2021-06-18 20:41 UTC, martis-git commented on src/pages/search/page.tsx
> +  }, [history, searchQuery]);
Точно не редиректить)

Можешь глянуть, как здесь сделано:
https://dev-sharead.netlify.app/catalog

Но я бы, для простоты - писал что-то вроде "Введите поисковую фразу" где-то рядом, возможно даже на самой поисковой странице (мб только по "клику" на поиск)

Надо посмотреть по UX как лучше, мб стоит даж согласовать в Димой

2021-06-18 20:42 UTC, martis-git commented on src/pages/search/page.tsx
> +        <p>Loading...</p>
Думаешь?))

2021-06-18 20:42 UTC, martis-git commented on src/pages/search/page.tsx
> +        <p>Loading...</p>
Или так по дизайну было?))

2021-06-18 20:44 UTC, martis-git commented on src/app/application.tsx
> +  </QueryParamProvider>
Ух прям руки чешутся в провайдеры повыносить))

Но out of scope офк

2021-06-18 20:45 UTC, martis-git commented on src/features/search-bar/lib.ts
> +}
Хотя я обычно создаю "params.ts" в ui-сегменте, но пока пофиг - некритично)

2021-06-18 20:45 UTC, martis-git commented
@OlegBrony пингани, как можно будет ревьювить

2021-06-19 01:42 UTC, OlegBrony commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
Я просто в упор проблемы не вижу...

2021-06-19 01:43 UTC, OlegBrony commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
Мне больше через точку нравится...

2021-06-19 01:45 UTC, OlegBrony commented on src/pages/search/model.ts
> +  cards_count: number;
Не вижу смысла "натягивать" бек. Пусть пишет как ему удобно, мы нормализуем.

2021-06-19 01:46 UTC, OlegBrony commented on src/pages/search/model.ts
> +  cards_count: number;
"snake_case в JS ну не юзается прост)))"
Да бладж
Это не жс код!

2021-06-19 01:49 UTC, OlegBrony commented on src/entities/user/types.ts
> +}
Ты издеваешься?
- как ты предлагаешь это пофиксить?
- предлагаю это пофиксить!

2021-06-19 01:53 UTC, OlegBrony commented on src/pages/search/page.tsx
> +import { useSearchQuery } from '@cardbox/features/search-bar';
Проблемы сортировщика 🤷

2021-06-19 01:55 UTC, OlegBrony commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
Да кто такие эти ваши селекторы? Мы чё, в ридаксе?

2021-06-19 09:39 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
@risenforces @sergeysova @antonmazhuto @dmi-ch Мнения?)

2021-06-19 09:40 UTC, martis-git commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
@risenforces @sergeysova @antonmazhuto @dmi-ch Мнения?)

2021-06-19 09:42 UTC, martis-git commented on src/pages/search/model.ts
> +  cards_count: number;
> Не вижу смысла "натягивать" бек. Пусть пишет как ему удобно, мы нормализуем.

API - это речь не только про бэк, но и про фронт)
Обе стороны должны принимать участие в ее проектировании

Бэк может писать как хочет и как удобнее, но это в конечном счете может дойти до неюзабельного состояния (т.к. фронт не посчитал нужны поговорить про это с бэком)

Или же вообще многие критические моменты, которые должны быть просчитаны на сервере, в итоге временно-постоянно остаются на клиенте 

А там и до security-issues недалеко дойти

2021-06-19 09:43 UTC, martis-git commented on src/pages/search/model.ts
> +  cards_count: number;
> "snake_case в JS ну не юзается прост)))"
> Да бладж
> Это не жс код!

@risenforces @sergeysova @antonmazhuto @dmi-ch Мнения?)

2021-06-19 09:43 UTC, martis-git commented on src/entities/user/types.ts
> +}
> Ты издеваешься?

Не кипятись)))

2021-06-19 09:45 UTC, martis-git commented on src/entities/user/types.ts
> +}
> @OlegBrony 
> - как ты предлагаешь это пофиксить?

> @martis-git 
> Предлагаю не кастовать "I" для интерфейсов (и "T" для типов) в TypeScript

2021-06-19 09:49 UTC, antonmazhuto commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
согласен @martis-git, возможно это работает, но так делать не приветсвуется

2021-06-19 09:49 UTC, martis-git commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
Концепция селекторов это не только про ридакс)

@dmi-ch @sergeysova @risenforces @antonmazhuto Поправьте если что, но по-моему в СТМ на каждый чих не оч создавать новый стор, гораздо проще сделать computed-селектор для UI, не?

2021-06-19 09:50 UTC, martis-git commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
А, ну Сергей вот кста еще про это писал

https://t.me/sergeysova/88

2021-06-19 10:00 UTC, dmi-ch commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
@martis-git а что именно ты подразумеваешь под созданием нового стора?  combine выше? в useStore просто useRef используется

2021-06-19 10:05 UTC, martis-git commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
Да, всякие combine для computed-свойств сторов - насколько знаю в эффекторе так можно делать, но имхо, как будто не всегда нужно)

Но тут думаю еще речь не только про это - но и про инкапсуляцию внутренней логики модели - тип гораздо антихрупче выходит, если выставить со стороны модели селекторы `useSearchQueryChanged` и `useLoading`

2021-06-19 10:05 UTC, martis-git commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
Сергей в упомянутом чуть выше посте - в принципе про это же говорит

2021-06-19 11:07 UTC, risenforces commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
Технически это одно и то же, но есть 2 поинта, почему лучше выносить хуки наверх:
- сразу видно все требуемые данные, не надо бегать глазами по всему компоненту и jsx
- при добавлении условного рендеринга и т.д. все будет ок, а с вызовами хуков в jsx - надо будет их все равно вынести наверх, т.к. хуки начнут условно вызываться и нарушится порядок

Обе вещи становятся особенно заметными при рефакторинге/добавлении новой логики

Ну и еще такой поинт: если есть 2 способа сделать то же самое, и первый из них работает всегда, а второй работает только в определенных ситуациях - логичнее выбрать первый, и это к тому же будет более консистентно (один и тот же способ по всей кодовой базе)

2021-06-19 11:26 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
> @risenforces Хуки через React. не хотелось бы

2021-06-19 11:27 UTC, martis-git commented on src/lib/use-query.ts
> +}
> @risenforces use-query странно, там наверное стоит lib/routing/use-query или что-то такое

2021-06-19 11:27 UTC, martis-git commented on src/pages/search/model.ts
> +  cards_count: number;
> @risenforces Вот про snake_case хз, это везде больно нормализовывать)

2021-06-19 11:28 UTC, martis-git commented on src/pages/search/model.ts
> +  cards_count: number;
@risenforces так тебе и не нужно будет это "везде" нормализовывать))

Если с бэком не удается договориться (вдруг), то ты просто добавляешь нормалайзер-хелпер базовый, и применяешь - "где болит" в `shared/api`

2021-06-19 11:32 UTC, martis-git commented on src/lib/use-query.ts
> +}
Ну либо так ~~кодим свои велосипеды~~, либо можно присмотреться к другим решениям

Лично я прост уже много таких реализаций за спиной имею, и честно говоря - задалбывает меня лично такое писать, плюс постоянно не хватает какого-то функционала)

Но я бы обсудил все это офк

2021-06-19 12:41 UTC, sergeysova commented on src/app/application.tsx
> +  <QueryParamProvider ReactRouterRoute={Route}>
А зачем это вообще?

2021-06-19 12:43 UTC, martis-git commented on src/app/application.tsx
> +  <QueryParamProvider ReactRouterRoute={Route}>
См. коммент

https://github.com/cardbox/frontend/pull/26#discussion_r654652322

2021-06-19 12:45 UTC, sergeysova commented on src/features/search-bar/lib.ts
> +}
А зачем такое?

2021-06-19 12:47 UTC, martis-git commented on src/features/search-bar/lib.ts
> +}
См. коммент

https://github.com/cardbox/frontend/pull/26#discussion_r654652322

2021-06-19 12:50 UTC, martis-git commented on src/features/search-bar/lib.ts
> +}
@sergeysova вот как пример применения
https://pastebin.com/D9jt2AzG

2021-06-19 12:59 UTC, sergeysova requested changes

2021-06-19 12:59 UTC, sergeysova commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
Я бы вообще заменил все это на @effector/reflect

2021-06-19 12:59 UTC, sergeysova commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
Не люблю завязки на реакт. Логику тупо не запустить на сервере, получается, без запуска реакт

по хорошему нужно юзать hatch https://github.com/accesso-app/admin/blob/master/src/pages/home/contract.ts#L3

в нем уже есть разобранные параметры query https://github.com/framework/framework/blob/master/src/hatch.ts#L11

тащить отдельную либо с провайдером для квери это оч странно, имхо

2021-06-19 12:59 UTC, sergeysova commented on src/pages/search/model.ts
> +  cards_count: number;
Так у нас весь бекенд в camelCase отправляет.
Код хоть и в snake_case, в апи отправляется через camelCase, как раз, чтобы фронт не страдал.

для OAuth по другому, там соблюдаем стандарт. А здесь лишь один клиент — фронтенд, делаем как удобно фронту

2021-06-19 12:59 UTC, sergeysova commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
Не не, такое не надо)

2021-06-19 12:59 UTC, sergeysova commented on src/pages/search/page.tsx
> +  }, [history, searchQuery]);
А вот дёргать Хистори напрямую кажется прям не оч, лучше импортную ивент https://github.com/cardbox/frontend/blob/master/src/entities/navigation/index.ts#L9

2021-06-19 12:59 UTC, sergeysova commented on src/pages/search/page.tsx
> +);
Отображение сколько нашёл, не нужно.
Тогда можно заменить это на reflect

2021-06-19 12:59 UTC, sergeysova commented on src/pages/search/page.tsx
> +}
Разницы никакой нет. Разве что семантически интерфейс лучше читается, а ведь попсы и являются интерфейсом компонента

2021-06-21 14:48 UTC, Drevoed commented on src/pages/search/model.ts
> +  cards_count: number;
У нас BFF, насколько я понимаю, поэтому отправлять будем так, как удобно фронту :)

2021-06-22 12:42 UTC, sergeysova commented on package.json
> -    "patronum": "^0.106.0",
Всё гораздо проще)

![image](https://user-images.githubusercontent.com/5620073/122926368-75bc3a80-d370-11eb-9d96-37e203c9ad60.png)

Нужно было четко отделить одну минорку от другой, но при этом не выпуская мажор

2021-06-22 12:43 UTC, sergeysova commented on package.json
> +    "react-tabs": "^3.2.2",
мб выпилить?

2021-06-22 12:43 UTC, sergeysova commented on package.json
> +    "through": "^2.3.8",
Кажется нигде не юзается

2021-06-22 12:44 UTC, sergeysova commented on src/lib/use-query.ts
> +}
Тащить для такого либу кажется совсем абсурд.

Всё что есть в этой либе уже есть в собственном коде, тот же start: https://github.com/cardbox/frontend/blob/master/src/lib/page-routing.ts#L12

2021-06-22 12:46 UTC, sergeysova commented on src/lib/use-query.ts
> +}
В дальнейшем затащим [framework](https://npmjs.com/framework), а там есть [hatch](https://github.com/framework/framework/blob/master/src/hatch.ts#L25)

Я не оч понимаю смысла тащить 12Кб кода для простейшей вещи, решаемой в 10 строк

2021-06-22 16:50 UTC, martis-git commented on src/lib/use-query.ts
> +}
> Я не оч понимаю смысла тащить 12Кб кода для простейшей вещи, решаемой в 10 строк

Обычно эти "10 строк" работают для базовых кейсов, но потом в определенный момент ебнется синхронизация параметров - и пам пам))

Предложи свою реализацию хука с параметрами - которая бы нормально юзалась - и можно закрыть вопрос без б)

2021-06-22 16:50 UTC, martis-git commented on src/lib/use-query.ts
> +}
Я вот прост сколько не реализую - постоянно какая-то херь появляется

Особенно когда хук для работы с одним параметром применяется в нескольких местах и мутирует параметр из нескольких мест

2021-06-22 16:52 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
Оке, щас можно забить - но оч хочется увидеть тогда, как ты предлагаешь такое написать)))

А то потом скоро код костылями покроется, т.к. без query-параметров никуда

2021-06-22 16:55 UTC, martis-git commented on src/pages/search/page.tsx
> +  const isShowLoading = useStore(model.$isShowLoading);
> Не не, такое не надо)

Оке оке, эффекторовцы захватили чат)))

2021-06-24 18:11 UTC, OlegBrony commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
классная штука, но багует с перерендерами. я не так приготовил?
```

const CardRes = reflect({
  view: CardList,
  bind: { cards: model.$searchResultCardList },
});

const UserRes = reflect({
  view: UserPreviewList,
  bind: { users: model.$searchResultUserList },
});
```
первый рендер на странице - ок, переключаю табу - минус.

2021-06-24 18:12 UTC, OlegBrony commented on src/features/search-bar/organisms/search-bar.tsx
> +  }, [query, searchValueChanged]);
пока оставлю так, интересно посмотреть что имеется в виду.

2021-06-24 18:13 UTC, OlegBrony commented on src/lib/use-query.ts
> +}
окей... так... мне вернуть как было - без пакета?

2021-06-24 18:16 UTC, OlegBrony commented on src/features/search-bar/models/index.ts
> +type ChangeEv = ChangeEvent<HTMLInputElement>;
убрал

2021-06-24 18:17 UTC, OlegBrony commented on src/features/search-bar/organisms/search-bar.tsx
> +          <Link to={paths.home()}>
а зачем? он один на странице, чем меньше пропсов - тем меньше связанности - тем лучше, не?

2021-06-24 18:22 UTC, OlegBrony commented on src/features/search-bar/molecules/search.tsx
> +      onChange={useEvent(model.searchFieldChanged)}
обнаружил ещё баг
заменил сёрч инпут на рефлект, получил кейс, когда не удаляется валье - если перезагрузить страницу поиска (то есть сделать так, чтоб на момент рендера было велье) - и попробовать удалить целиком (ctrl + backspace or ctrl + a, backspace) - оно не удаляется. грешу на useEvent. я неправильно рефлект приготовил?

2021-06-24 18:24 UTC, OlegBrony commented on src/features/search-bar/molecules/search.tsx
> +      placeholder="Search placeholder"
надо обсудить поведение, я до конца не понимаю что от меня хотят.

2021-06-24 18:24 UTC, OlegBrony commented on src/pages/search/model.ts
> +);
тут пока хз, что сказать. помечу как резолвд.

2021-06-24 18:27 UTC, OlegBrony commented on src/pages/search/model.ts
> +);
я всё ещё не понимаю, как мне нужно мой код изменить.
у меня на один запрос типа получаются и юзеры и  карточки. я и сохранил их в отдельные сущности.

2021-06-24 18:34 UTC, OlegBrony commented on src/pages/search/page.tsx
> +  }, [history, searchQuery]);
> Точно не редиректить)

сейчас никуда не редиректит. это ивент на случай, если юзер открыл линку as `https://localhost:3000/search?query=`

2021-06-24 18:40 UTC, OlegBrony commented on package.json
> +    "react-tabs": "^3.2.2",
а как тогда?

2021-06-24 18:41 UTC, OlegBrony commented on package.json
> +    "through": "^2.3.8",
я это добавил? о_О

2021-06-24 18:43 UTC, OlegBrony commented on package.json
> +    "through": "^2.3.8",
![image](https://user-images.githubusercontent.com/19880334/123316181-3b4fca80-d535-11eb-8dbe-465005baed4c.png)
нет, не я

2021-06-24 18:46 UTC, martis-git commented on package.json
> +    "react-tabs": "^3.2.2",
WolyUI заюзать?

2021-06-24 18:46 UTC, martis-git commented on src/app/application.tsx
> +// import 'react-tabs/style/react-tabs.css';
А че бы не удалить?

2021-06-24 18:57 UTC, martis-git approved these changes
В принципе все ок. Я бы уже заливал как есть т.к. оч давно тянется PR 

Но христа ради - удали package-lock пож)

2021-06-24 18:57 UTC, martis-git commented on src/app/application.tsx
> +import { QueryParamProvider } from 'use-query-params';
Круто, спасиб что добавил

Но если @sergeysova попросит удалить / заменить (а он вродь примерно такое и просил) - то лучше послушай его)

Я особо не топлю прям, но мне тож вот интересно "А как иначе тогда?"

2021-06-24 18:57 UTC, martis-git commented on src/app/application.tsx
> +  }
Мб в `app/styles/vars.css` засунуть сразу?

Хотя некритично, если других глобальных стилей не заводилось до этого (да и тем более раз у нас стайледы)

2021-06-24 18:57 UTC, martis-git commented on src/entities/card/organisms/card-list.tsx
> +      <CardPreview key={card.id} card={card} isCardInFavorite={i % 2 === 0} />
Йее, псевдозначения наше все))

> Не в упрек если что говорю, сам такое практикую, когда нет реальных данных

2021-06-24 18:57 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +} from '../../../ui';
А это не то же, что и `@cardbox/ui`?

2021-06-24 18:57 UTC, martis-git commented on src/entities/user/lib.ts
> +  const lowerQuery = query.toLowerCase();
Чет туплю - а в чем отличие query от search?

2021-06-24 18:57 UTC, martis-git commented on src/entities/user/lib.ts
> +}
Выглядит заморочисто - но пофиг, если пока работает то лан)

2021-06-24 18:57 UTC, martis-git commented on src/features/search-bar/lib.ts
> +}
`withDefault` есть для дефолтных значений - глянь в доке

> Но это офк на случай, если оставляем `use-query-params`, @sergeysova  уточни

https://github.com/pbeshai/use-query-params/tree/master/packages/use-query-params#readme

2021-06-24 18:57 UTC, martis-git commented on src/pages/card/index.tsx
> +        <CardPreview card={card} isCardInFavorite={false} />
Некритично, но можно просто `isFavorite`

2021-06-24 18:57 UTC, martis-git commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
Это скорее про то, что ты в роутинг не можешь заранее заложить все-все варианты использования query-параметров

Да и это не нужно по сути , т.к. это про разное

2021-06-24 18:57 UTC, martis-git commented on src/ui/atoms/button.tsx
> +  color: var(--wizard500);
А такие названия цветов прям с макета?

2021-06-24 18:57 UTC, martis-git commented on src/ui/icons/index.ts
> +export { default as iconDeckArrow } from './deck-arrow.svg';
Для консистентности, давай хоть все будет с большой буквы , т.к. компоненты))

2021-06-24 18:57 UTC, martis-git commented on package.json
>      "lint": "eslint --fix ./src"
Нужно удалить package-lock и юзать yarn 

Только щас заметил лул

2021-06-24 18:57 UTC, martis-git commented on package.json
>      "lint": "eslint --fix ./src"
Это вот прям оч важно

Желательно еще снести все node_modules и установить заново через yarn - чтобы yarn.lock точно установился

2021-06-24 19:03 UTC, sergeysova commented on package.json
> +    "react-tabs": "^3.2.2",
А зачем тащить либу для простейших табов

Разве у нас там вообще были табы в дизайне?

2021-06-24 19:06 UTC, sergeysova approved these changes

2021-06-24 19:07 UTC, merged

2021-08-04 21:30 UTC, azinit commented on src/pages/paths.ts
> +    if (query) return `/search?query=${query}`;
https://linear.app/atomix/issue/BOX-182/popravit-rabotu-s-query-params