BOX-60 BOX-26 User page and card view page
cardbox/frontend pull request #27
Opened 2021-06-10 18:00 UTC by antonmazhuto

### feat/user-profile

2021-06-16 23:02 UTC, martis-git requested changes
В целом - оч добротно, но некоторые моменты бы поправил всеж

Возможно со второй итерации еще что вылезет, но в целом есть что улучшить еще)

2021-06-16 23:02 UTC, martis-git commented on src/pages/user/index.tsx
>  export const UserPage = () => (
По странице:

1. Некритично, но я бы добавил разные выборки карточке в зависимости от активного таба (делается несложно, зато сразу базовая логика закладывается)

![image](https://user-images.githubusercontent.com/42924400/122305474-99febe00-cf0f-11eb-840f-c00b97ec2405.png)

2. На странице профиля есть базовая инфа частями - а местами жесткие заглушки

Привести бы к одному виду - это ведь все равно локальные фикстуры))

Заодно под формат API и юзера можно заложиться

![image](https://user-images.githubusercontent.com/42924400/122305495-aa169d80-cf0f-11eb-99c7-20346725462f.png)

3. Некритично, но кнопки не доступные для функционала (Edir Profile / Save Card и т.п. ) - я бы дизейблил до той поры , пока для них нет реализации логики (хотя бы до mock-овой)

2021-06-16 23:02 UTC, martis-git commented on src/pages/user/index.tsx
>  export const UserPage = () => (
Макеты не смотрел пока, но остальное все оч даже выглядит

2021-06-16 23:02 UTC, martis-git commented on src/pages/home/index.tsx
> +  //width: 74.5%; /* 1044 / 1404 * 100 */
А разве по задаче нужно было home-page затрагивать? Или это партизанские доработки?)

2021-06-16 23:13 UTC, martis-git commented
Плюс я бы более осмысленное описание изменений делал

И тебе проще рефлексировать "А не задел ли я что-то лишнее по задаче?" и ревьюверу проще понять, что тут происходит
(и тебя меньше вопросами будет заваливать)

![image](https://user-images.githubusercontent.com/42924400/122306637-79cffe80-cf11-11eb-9fdc-5d61dfc9ec2e.png)

2021-06-17 07:00 UTC, martis-git commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
Кста, тольк щас заметил - а поч с маленькой буквы? Обычный React компонент же, насколько понимаю

2021-06-19 13:18 UTC, sergeysova commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
```jsx
<button.Text />
```

2021-06-19 13:31 UTC, martis-git commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
Ну эт да, понимаю

Но этож все равно компонент самостоятельный должен быть по задумке Compound Components, не?)

```ts
// 1
<Button />
// 2
<Button.Text />
// 3
<Button.Link />
// 4
<Button.Group>
   ...
</Button.Group>
```

https://kentcdodds.com/blog/compound-components-with-react-hooks

2021-06-25 10:06 UTC, sergeysova commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
Не обязательно следовать

2021-06-25 10:06 UTC, sergeysova commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
Плюс у функции тонны своих свойств, и в тс оч сложно идентифицировать их

2021-06-25 10:15 UTC, martis-git commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
> Не обязательно следовать

Ну хз, это же тупо как конвенция называть компоненты с большой буквы))

Да и при импорт компонента `button` - хоть как есть ожидание , что можно заюзать как его самого (<Button>) так и дочерние элементы если есть (<Button.Text/>)

2021-06-25 10:16 UTC, martis-git commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
> Плюс у функции тонны своих свойств, и в тс оч сложно идентифицировать их

Да чет вродь не было проблем при типизации подобных компонентов)

Я тут скорее за то, что в lowerCase компонент написан негодую

2021-06-28 16:10 UTC, OlegBrony commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
на самом деле в данном случае lowerCase очень уместен.
1. я не ожидаю, что Button (не Button.Some, а просто Button) - компонент. я точно знаю, что это __только__ неймспейс.
1. var name 'Button' не занято! даже в этом пр я где-то видел, что можно
импортнуть ` import { button }`
сделать стиль `const Button = styled(button.Some)```
и использовать `<Button></>`
ну круто же!

2021-07-01 07:00 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +import { IconSave } from '../../../ui';
fixed

2021-07-01 07:00 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +        <Link to={`/card/${card.id}`}>
fixed

2021-07-01 07:00 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +  };
deketed

2021-07-01 07:03 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
removed

2021-07-01 07:04 UTC, antonmazhuto commented on src/features/search-bar/organisms/search-bar.tsx
> +          <Link to="/user">
fixed

2021-07-01 07:09 UTC, antonmazhuto commented on src/features/search-bar/organisms/search-bar.tsx
> +              <Avatar src="https://images.pexels.com/photos/2927811/pexels-photo-2927811.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" />
fixed

2021-07-01 07:15 UTC, antonmazhuto commented on src/features/tabs/molecules/index.ts
> +export { TabTitle } from './title';
fixed

2021-07-01 07:16 UTC, antonmazhuto commented on src/pages/card/index.tsx
> +);
deleted

2021-07-01 07:20 UTC, antonmazhuto commented on src/ui/icons/index.ts
> +export { default as UserBg } from './user_bg.svg';
fixed

2021-07-01 07:30 UTC, antonmazhuto commented on src/pages/user/index.tsx
>  export const UserPage = () => (
fixed

2021-07-01 07:30 UTC, antonmazhuto commented on src/pages/home/index.tsx
> +  //width: 74.5%; /* 1044 / 1404 * 100 */
fixed

2021-07-01 07:31 UTC, antonmazhuto commented on src/pages/user/index.tsx
> +    </ContentCenteredTemplate>
fixed

2021-07-01 07:35 UTC, antonmazhuto commented on src/entities/card/model.ts
> +
deleted

2021-07-02 19:42 UTC, martis-git approved these changes
Есть что улучшить офк, но я бы лично поправил это позж, а пока залил бы как есть))

А то сколько времени уже тянем

2021-07-02 19:42 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +      {/*<Container>*/}
Твоя любовь к комментарием все не отпускает тебя, да?)

2021-07-02 19:42 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
>  import { paths } from '../../../pages/paths';
Некритично, но я бы уже начинал абсолютные пути юзать
```suggestion
import { avatarUri } from '@box/shared/constants';
import { paths } from '@box/pages/paths';
```

2021-07-02 19:42 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +          <Link to="/user">
Все равно в итоге роут остается на уровне фичи))

Пока некритично, но потом больно будет скорей всего

2021-07-02 19:42 UTC, martis-git commented on src/pages/user/index.tsx
> +  const reversedCards = [...cards].reverse();
У тебя эта операция каждый рендер будет происходить

Некритично, но я бы в самой модели смаппил

`$cards.map(...)` (насколько помню так в эффекторе делается)

2021-07-02 19:42 UTC, martis-git commented on src/pages/user/index.tsx
> +  margin-bottom: 8.25rem;
Ух как много компонентов)))

Но лан, потом задекомпозим

2021-07-02 19:42 UTC, martis-git commented on src/shared/constants.ts
> +export const avatarUri =
Потом из вьювера сможешь брать)

2021-07-02 19:42 UTC, martis-git commented on src/ui/molecules/title.tsx
> +  }, [setSelectedTab, index]);
Пока ОК, но не забывай))

https://github.com/atomix-team/codestyle/blob/master/codestyle.md#11-access-to-internal-resources

2021-07-02 20:31 UTC, sergeysova approved these changes

2021-07-02 20:32 UTC, merged

2021-07-02 21:21 UTC, martis-git commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
@OlegBrony 

1) Глянь как сделано у известных UIKit систем)

- [Ant.design](https://ant.design/components/layout/)
- [(и упаси боже) react-bootstrap](https://react-bootstrap.github.io/components/cards/)

Я в принципе понимаю случаи, когда с маленькой буквы, только потому что нейспейс (и то похоливарил бы, но тут субъективщина)

Но когда для подобных компонентов принципиально забивается возможность заиспользовать как дефолтный компонент... Немног диссонирует))

> `<button.Base/>` вместо `<Button />` - серьезно?? 😄 


2) Ну тож такое))

Щас под такой довод можно тогда и для других вещей нейминг коряжить, лишь бы под стайлед нашелся нейминг 
*(что в принципе является уже скорее проблемой стайледа а не Compound.Components)*

2021-07-03 03:11 UTC, OlegBrony commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
Тебе не угодишь.

2021-07-03 03:13 UTC, OlegBrony commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
Это решает проблемы, но тебе просто не нравится как выглядит. Без аргументов.

2021-07-03 03:53 UTC, martis-git commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
@OlegBrony 

> Тебе не угодишь. Это решает проблемы

Да не, я рили пытаюсь понять в чем тут преимущество значительное

> но тебе просто не нравится как выглядит. Без аргументов.

Ну не без этого, т.к. обычно когда ты импортируешь из UIKit "button" - есть большое ожидание, что его можно заюзать как компонент напрямую

А учитывая что оно с малой буквы, так и еще зачем-то компонент в `button.Base` засунули... Ну прост смысла не вижу усложнять разрабам жизнть так

2021-08-04 21:14 UTC, azinit commented on src/features/search-bar/organisms/search-bar.tsx
> +          <Link to="/user">
https://linear.app/atomix/issue/BOX-178/ubrat-deklaraciyu-routov-nizhe-sloya-pages

2021-08-04 21:17 UTC, azinit commented on src/features/tabs/molecules/title.tsx
> +import { button } from '@cardbox/ui';
https://linear.app/atomix/issue/BOX-179/uluchshit-realizaciyu-uikit

2021-08-04 21:18 UTC, azinit commented on src/pages/user/index.tsx
> +  margin-bottom: 8.25rem;
https://linear.app/atomix/issue/BOX-180/dekompozirovat-stranicu-userpage

2021-08-04 21:19 UTC, azinit commented
Будет пофикшено по:
https://linear.app/atomix/issue/BOX-180/otrefachit-stranicu-userpage