BOX-97: Implement CardEdit logic
cardbox/frontend pull request #43
Opened 2021-07-14 23:49 UTC by martis-git

### Branch name
  
  - [ ] Your branch should be prefixed with `feature/` or `fix/` or `chore/` or `refactor/` or `tests/`
  - [ ] Add issue identifier
  - [ ] Add 3-5 words of description separated with `-`
  
  Example:
  
  ```
  feature/BOX-12-add-login-form
  fix/BOX-8-loading-panel-on-first-load
  chore/BOX-22-add-release-drafter
  ```
  
  ### PullRequest
  
  - [ ] This PullRequest implements new feature, fix bug, or some other changes
  - [ ] If PR is not ready to review mark it as Draft
  - [ ] All commits in this PR should be created by `yarn commit` by [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - [ ] Title of the PullRequest should have issue(s) identifier(s) ("BOX-123 Example title of PR")

2021-07-15 03:10 UTC, martis-git reviewed
self-reviewed

2021-07-15 03:10 UTC, martis-git commented on src/api/mock/fixtures.ts
> +import { getValueNode } from '@box/lib/editor';
Скорее всего потом вообще этот хелпер выпилим, но пока он нужен

2021-07-15 03:10 UTC, martis-git commented on src/api/mock/fixtures.ts
> +  JSON.stringify(getValueNode(content));
Потом посмотрим как лучше нормализовать фикстуры)

2021-07-15 03:10 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +          <Editor value={JSON.parse(content)} readOnly={true} />
Везде так много `JSON.parse` и `JSON.stringify` т.к. изначально в модели карточки `content: string`, и чтобы не перекосоебить проект от двух разных типов - лучше уж все сводить к стринге

2021-07-15 03:10 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +  max-height: 90px;
@risenforces Спасибо!)

2021-07-15 03:10 UTC, martis-git commented on src/features/card/actions/model.ts
> +});
Оч хотел сразу привязываться к стору через какой-нить `attach`, но тогда у меня сохранение переставало работать 😄

2021-07-15 03:10 UTC, martis-git commented on src/features/card/actions/ui/edit-content.tsx
> +  }
Йей богу, вот пытался обойтись стайледами, но не переопределяются стили и все)))

Пришлось по-старинке....

2021-07-15 03:10 UTC, martis-git commented on src/features/card/actions/ui/index.ts
> +export * from './edit-content';
Похоливарим что фича, а что нет? 😎

2021-07-15 03:10 UTC, martis-git commented on src/features/card/actions/ui/reset-changes.tsx
> +        if (!window.confirm(CANCEL_WARN)) return;
Тож как woly втянем или допилим проектный UIKit - уберем такие моменты нафиг

Но пока **имеем шо имеем**

2021-07-15 03:10 UTC, martis-git commented on src/pages/card/edit/index.tsx
> +`;
Потенциально можно вынести в `shared/ui/layout`, но есть ощущение что это пока онли для этой страницы такие стили

2021-07-15 03:10 UTC, martis-git commented on src/pages/card/edit/index.tsx
> +`;
Возможно потом вынесу чисто ради "семантики" и базовых стилей

2021-07-15 03:10 UTC, martis-git commented on src/pages/card/edit/model.ts
> +    return cardId ? paths.card(cardId) : paths.home();
**ВОТ ТУТ АХТУНГ ПОЛНЫЙ**

В ообщем, изначально эта реализация была через return-значения от события и эффекта (т.е. каждый так или иначе позволял достать cardId из респонса)

Потом я подумал "Не, так точно оставлять нельзя, айда 'по-умному' сделаем"

И по итогу - для resetChanges такая логика работает, а для эффекта почему-то нет (т.е. cardId === null и редиректит на хоум соответственно)

Гуру эффектора подскажите пож, где продолбался?
*(вродь и аттачи разные пробовал, и разделять, и локально стор только хранить с cardId - крч результат один и тот же, а иногда даж и хуже)*

@risenforces @sergeysova @dmi-ch @antonmazhuto @asvtsv @OlegBrony

2021-07-15 03:10 UTC, martis-git commented on src/pages/card/index.ts
> +export { CardPage } from './view';
Учитывая, что еще будет отдельно страница "Create" (скорее всего отдельно) - показалось опять же - что лучше сразу так разделить

2021-07-15 03:10 UTC, martis-git commented on src/pages/routes.ts
> +  { exact: true, path: paths.cardEdit(':cardId'), component: CardEditPage },
Возможно такие моменты планировалось получше обрабатывать

@sergeysova дай знать если что

2021-07-15 07:46 UTC, martis-git commented
@cardbox/core гляньте пож

2021-07-15 08:43 UTC, risenforces commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
Верни)

2021-07-15 08:43 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
Будем драцца....

2021-07-15 11:26 UTC, sergeysova requested changes

2021-07-15 11:26 UTC, sergeysova commented on src/pages/card/edit/model.ts
> +import { paths } from '../../paths';
```suggestion
import { paths } from '@box/pages/paths';
```

nitpick: Кажется лучше использовать абсолютный путь

2021-07-15 11:26 UTC, sergeysova commented on src/pages/card/edit/model.ts
> +});
nitpick: я бы разделил флоу на две части, одно для reset, другое для сохранения.

```suggestion
sample({
  clock: changesReset,
  target: historyPush.prepend(paths.home),
})

sample({
  source: $currentCardId,
  clock: changesSubmitFx.done,
  target: historyPush.prepend(path.card),
})
```

2021-07-15 11:26 UTC, sergeysova commented on src/pages/card/index.ts
> +export { CardPage } from './view';
suggestion: не стоит создавать отдельный index для группы страниц, ибо будет сложно импортировать, особенно добавлять разделение по чанкам. Лучше свести все импорты в `pages/routes`

nitpick: У тебя название компонента отличается от названия файла (CardEditPage -> edit), но (CardPage -> view), лучше тогда назвать `CardViewPage`.

2021-07-15 11:26 UTC, sergeysova commented on src/features/card/actions/ui/update-changes.tsx
> +};
suggestion(non-blocking): Можно переписать на reflect:

```suggestion
export const UpdateChanges = reflect({
  view: button.Primary,
  bind: {
    onClick: submitChangesPressed,
    disabled: $draft.map(draft => !draft),
    children: 'Save',
  },
})
```

issue: Здесь данные из стора передаются в ивент во вью, а это часть логики.
suggestion: Можно запросто взять данные из draft в момент вызова submitChanges, например через sample. Тогда вьюхе это просто не нужно будет знать.

issue: Аналогично с disabled. Причина по которой кнопка должна отключаться это тоже часть модели.
suggestion: Лучше из модели экспортировать соответствующий стор `$disabled`

```suggestion
export const UpdateChanges = reflect({
  view: button.Primary,
  bind: {
    onClick: submitChangesPressed,
    disabled: $isSubmitDisabled,
    children: 'Save',
  },
})
```

nitpick: Я не особо вижу смысла выносить такой простейший компонент в фичу, тогда как он решается одним простейшим reflect и он напрямую прибит к логике и фактически не является реюзабельным

2021-07-15 11:26 UTC, sergeysova commented on src/pages/card/view/index.tsx
> +import { paths } from '../../paths';
```suggestion
import { avatarUri } from '@box/shared/constants';
import { paths } from '@box/pages/paths';
```

nitpick: тут кажется тоже лучше абсолютный путь

2021-07-15 11:26 UTC, sergeysova commented on src/pages/card/view/index.tsx
> +              {card && (
issue: редактировать карточку может только автор, а значит нужна проверка

2021-07-15 13:01 UTC, risenforces commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
**suggestion**:

```suggestion
type CardMode = 'preview' | 'full';
```

2021-07-15 17:22 UTC, martis-git commented
![image](https://user-images.githubusercontent.com/42924400/125830481-3d09c583-804d-4a2a-b48d-b8fb417dfec1.png)

2021-07-15 21:56 UTC, martis-git commented on src/pages/card/view/index.tsx
> +import { paths } from '../../paths';
Только за, просто я этот код не трогал, лишь переименовал)

2021-07-15 21:56 UTC, martis-git commented on src/pages/card/view/index.tsx
> +import { paths } from '../../paths';
Хотя к `paths` оставил бы всеж относительный импорт, т.к. это +- внутренний ресурс

2021-07-15 21:57 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +          <Editor value={JSON.parse(content)} readOnly={true} />
Принято, поправим)

2021-07-15 22:00 UTC, martis-git commented on src/pages/card/index.ts
> +export { CardPage } from './view';
(suggestion) Согл, тож не до конца был уверен

2021-07-15 22:01 UTC, martis-git commented on src/pages/card/index.ts
> +export { CardPage } from './view';
(nitpick) Меня тож чутка корежило, но казало перебор будет `CardViewPage` называть

Но лан, переименуем)

2021-07-15 22:02 UTC, martis-git commented on src/pages/routes.ts
> +  { exact: true, path: paths.cardEdit(':cardId'), component: CardEditPage },
(question) То, что возможно роутинг страниц "карточек" должен конфигурироваться на уровне `pages/cards/**`, а не на самом верху "в плоском виде"

Мб зря нагоняю 🤷

2021-07-15 22:03 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
(nitpick) Как и `preview`))

![image](https://user-images.githubusercontent.com/42924400/125863610-374aa088-e365-416b-a412-91e61f0bd3a5.png)

2021-07-15 22:06 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
Ну вот насчет нейминга хз даж

У меня четкие ассоциации:
- `CardItem` - элемент чего-то большего, какой-то коллекции, как ListItem
- `CardDetails` - детали по карточке, в более развернутом виде

2021-07-15 22:16 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
Надо крч подумать еще, да....

2021-07-15 22:17 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
@dmi-ch @asvtsv @Kater-auf-Dach @antonmazhuto Что думаете?

2021-07-15 22:28 UTC, martis-git commented on src/features/card/actions/model.ts
> +export const $draft = createStore<Draft>(null);
question: Есть ощущение, что от такого разбиения мы скорее проиграем, чем выиграем)

Можно было сделать условный event, где за раз можно было бы обновлять все поля

Можешь пож развернуть, какой профит мы получим от такой атомарности?

(особенно когда в карточке будет чуть больше полей, чем просто `title,content,tags` - а еще ведь computed-сторы стоит учитывать

2021-07-15 22:31 UTC, martis-git commented on src/features/card/actions/model.ts
> +);
**question**: Так они энивей будут nullable в начале - пока не подгрузится инфа по карточке)

Да, мы получаем так более короткие редьюсеры, но как будто мы вместе с тем и получаем `Low Coupling & Low Cohesion` - что тож нам не на руку

А как ты без nullable хочешь эти "атомарные" сторы обрабатывать?

![image](https://user-images.githubusercontent.com/42924400/125865982-1a484c57-8b90-408b-a0c1-d25e3e6ab3df.png)

2021-07-15 22:33 UTC, martis-git commented on src/features/card/actions/model.ts
> +$draft.reset(resetChanges);
**question:** Вот имхо - это прям как раз четко показывает минусы таких атомарных сторов))

Я могу заблуждаться сильно как редаксоид и ньюфаг в эффекторе, но чет пока от этой концепции больше вреда чем пользы))

Тип, я просто хочу сбросить значение "черновика" до дефолтного, и приходится делать либо кучу шаблонного кода ("каждый стор отдельно"), либо же подтягивать лишние абстракции (привет доменам)

> Без агрессии, просто рили пока не въезжаю))

2021-07-15 22:35 UTC, martis-git commented on src/features/card/actions/model.ts
> +});
Ну я вот тож что-то вроде гарда хотел затащить

Но оке, сделаем

2021-07-15 22:39 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
> Вообще не понятно что располагается здесь, какие actions? что они делают? для чего? какую задачу решают?

Это как раз иллюстрация идеи из feature-sliced, когда мы не просто делаем под каждое действие свою фичу, а когда есть набор слишком связанных друг с другом действий - объединяем их в одну фичу (тем более они и с одним стором работают)

2021-07-15 22:42 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
>  По идее любой код в features/*/model должен быть фабрикой, и в крайне редком случае создавать свои локальные сторы

Почему ? Допустим вынесу я стор на уровне entities, а в модели оставлю лишь форфарды и обработку событий

А в чем профит?

2021-07-15 22:47 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
>  Если создаешь фабрику, то нужно путь к ней (то как будешь импортить, в данном случае путь к фиче, к индексу) добавить в babel effector plugin:

Как я понимаю, ты предлагаешь сделать фабрику, чтобы юзать больше одной фичи на странице, чтобы не было завязка на один инстанс стора фичи

Но имхо, пока это оверкилл, т.к. мы просто делаем редактирование карточки, и можно создать фабрику, когда это пригодится

2021-07-15 22:48 UTC, martis-git commented on src/pages/paths.ts
> +  cardEdit: (cardId: string) => `/card/${cardId}/edit`,
Оке, не против

@dmi-ch @risenforces @asvtsv @antonmazhuto @Kater-auf-Dach @Drevoed @OlegBrony а вы как?

2021-07-15 22:49 UTC, martis-git commented on src/entities/card/model/index.ts
> +);
Привет нормализованный стор 😏

2021-07-15 22:50 UTC, martis-git commented on src/entities/card/model/index.ts
> +);
Но имхо, тогда затруднится обработка подгрузки текущей карточки

Разве что сразу стор нормализовать и по айдишнику обновлять

**suggestion:** Но опять же, как мне кажется - лучше это делать вне этой задачи, т.к. уже слишком большой скоуп получается, и надо везде править по проекту

2021-07-15 22:51 UTC, martis-git commented on src/features/card/actions/index.ts
> +export * as cardActionsModel from './model';
Отписал про фабрики выше, го там разрулим)

2021-07-15 22:51 UTC, martis-git commented on src/pages/card/edit/model.ts
> +import { paths } from '../../paths';
Хз вот, это же +- внутренний ресурс)))

2021-07-15 22:52 UTC, martis-git commented on src/pages/card/edit/model.ts
> +});
Не-не, тут соль же в том, что `paths.home` это fallback-страница, в случае если вдруг внезапно cardId не будет задан к этому моменту (он же nullable у нас, не забываем)

2021-07-15 22:54 UTC, martis-git commented on src/features/card/actions/ui/update-changes.tsx
> +};
>  Можно переписать на reflect

Переписать то можно, а какой профит?)

Если захочется потом что-то поправить в логике,то придется шаманить с этими reflect-декларациями, и то скорей всего придется явно объявлять компонент, т.к. у нас не будет доступа к самой разметке и логике компонента

ИМХО, здесь излишне)

2021-07-15 22:55 UTC, martis-git commented on src/features/card/actions/ui/update-changes.tsx
> +};
> Можно запросто взять данные из draft в момент вызова submitChanges, например через sample. Тогда вьюхе это просто не нужно будет знать.

Да, мне тож моя версия не особо заходит, но там с аттачем стора в модели почему-то не работало

Но пробнем еще раз значит ~(с v0 же не спешим :D)~~

2021-07-15 22:55 UTC, martis-git commented on src/features/card/actions/ui/update-changes.tsx
> +};
> Лучше из модели экспортировать соответствующий стор $disabled

Оки, согл

2021-07-15 22:56 UTC, martis-git commented on src/features/card/actions/ui/update-changes.tsx
> +};
>  Я не особо вижу смысла выносить такой простейший компонент в фичу, тогда как он решается одним простейшим reflect и он напрямую прибит к логике и фактически не является реюзабельным

Мне кажется, или с таким подходом можно вообще тогда забить на слои и делать все на уровне страниц, которые будут разбухать?))

**Мыж вроде за тонкие страницы были**

**И при этом, чтобы логика была расфасована по скоупа ответственности (тобишь по слоям)**

2021-07-15 22:57 UTC, martis-git commented on src/pages/card/view/index.tsx
> +              {card && (
Немного OutOfScope, скорее всего отдельной задачей сделаю)

Тут пока цель была по задаче базовое редактирование завезти

(и то много изменений все равно для простой задачи)

2021-07-15 22:57 UTC, martis-git commented on src/pages/card/view/index.tsx
> +              {card && (
Но спасибо за напоминание

2021-07-15 23:00 UTC, martis-git commented on src/pages/card/view/index.tsx
> +              {card && (
https://linear.app/atomix/issue/BOX-161/dobavit-ogranichenie-na-prava-po-redaktirovaniyu-kartochki

2021-07-15 23:05 UTC, sergeysova commented on src/pages/routes.ts
> +  { exact: true, path: paths.cardEdit(':cardId'), component: CardEditPage },
Чем площе, тем легче обрабатывать

2021-07-15 23:08 UTC, sergeysova commented on src/features/card/actions/model.ts
> +export const $draft = createStore<Draft>(null);
У тебя никогда не будет ситуации, когда ты обновляешь все поля сразу(кроме загрузки значений с сервера). Юзер обновляет их всегда по отдельности. Зачем лишний раз триггерить рендер?
Ну и плюс, это Буквально подход эффектора, причем проверенный.

2021-07-15 23:09 UTC, sergeysova commented on src/features/card/actions/model.ts
> +);
Нужно записать во все эти сторы вменяемое начальное значение. Вьюха просто не будет рендерить компоненты со значениями из сторов во время загружки, если посчитает так нужным

2021-07-15 23:12 UTC, sergeysova commented on src/features/card/actions/model.ts
> +$draft.reset(resetChanges);
Ну тогда ты либо тянешь огромные и тяжелые спреды, либо иммер с теми же проблемами. И при этом обновляешь все компоненты черновика при изменении заголовка(представь какого будет редактору).
А чтобы не изменять будешь юзать селекторы, как в редаксе.
Этот подход позволяет четко отделить, в один стор кладутся либо списки, либо значения изменяемые всегда вместе. Все остальное в разные сторы

2021-07-15 23:12 UTC, sergeysova commented on src/features/card/actions/model.ts
> +$draft.reset(resetChanges);
Так намного проще работать, не таща спреды и иммер

2021-07-15 23:13 UTC, sergeysova commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
Давай созвонимся и обсудим, это долго писать

2021-07-15 23:14 UTC, sergeysova commented on src/entities/card/model/index.ts
> +);
Лучше править там, где твой скоуп. А не везде, где похожий подход

2021-07-15 23:16 UTC, sergeysova commented on src/pages/card/edit/model.ts
> +});
Тут именно смысл в том, чтобы разделить два сценария и сделать их наглядными и легкими для чтения.

в оригинальном варианте появляются условия. А это показатель, что более чем один сценарий вписан в выражение

2021-07-15 23:17 UTC, sergeysova commented on src/features/card/actions/ui/update-changes.tsx
> +};
Рефлект нужен, чтобы покрывать как раз такие кейсы. если сделано не на нем это сразу бросается в глаза, мол «смотри, тут не на рефлекте, значит что-то особенное и не тривиальная логика отображения»

2021-07-15 23:19 UTC, sergeysova commented on src/features/card/actions/ui/update-changes.tsx
> +};
> Мыж вроде за тонкие страницы были
Не стоит впадать в крайность, так можно и каждый стор с ивентом вынести

кнопка отправки это просто кнопка, здесь нет никакой логики

2021-07-15 23:22 UTC, sergeysova commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
> когда есть набор слишком связанных друг с другом действий

но под actions можно подвести абсолютно все действия с карточкой: удаление, сохранение в избранное, в бокс, архивация, восстановление, создание, редактирование, просмотр, удаление из бокса, удаление из избранного, комментирование.

это слишком абстрактно. Имя поэтому и не говорит ни о чем

2021-07-15 23:24 UTC, sergeysova commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
> можешь накидывать свои варики

DRAFT
Не все действия, а обработка черновиков. Не больше. Редактирование другая процедура, как и создание.

а вот работу с черновиками(в виде фабрики) можно переиспользовать в страницах создания и редактирования

2021-07-15 23:29 UTC, sergeysova commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
> > По идее любой код в features/*/model должен быть фабрикой, и в крайне редком случае создавать свои локальные стор
> 
> Почему ? Допустим вынесу я стор на уровне entities, а в модели оставлю лишь форфарды и обработку событий
> 
> А в чем профит?


Потому что тогда, ты будешь разделять эту логику и состояние сразу с десятком страниц и фич. Модификация этого состояния станет крайне опасным действием. Ведь тогда, ты не сможешь узнать заранее сколько и ГДЕ сломается в проекте или как это изменение повлияет на другие фичи, если не прочитаешь весь код проекта, который писал не ты.

Любые не локальные сторы должны использоваться по минимуму в фичах. Фабрика позволяет создать инстанс фичи в любой момент, а созданный стор и привязанный к нему компонент уже не даст тебе еще раз разместить его на странице

2021-07-15 23:35 UTC, sergeysova commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
> имхо, пока это оверкилл

Имхо, оверкилл это вытаскивать не переиспользуемую логику в фичи.

В страницах должен быть код, который используется только в странице. А сейчас открыв страницу я вижу там каплю кода, а остальное размазано ровным слоем по всему проекту.

Фабрики позволяют дать им четкое назначение, таким образом скрыв детали реализации от читателя кода страницы. Он увидит там фабрику, по названию поймет что она делает и не будет отвлекаться на чтение кода работы с локалСтораджем, а будет читать только то, что является особенностью конкретно этой страницы

2021-07-16 06:05 UTC, dmi-ch commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
Я где то до этого уже тоже отмечал, что    item выглядит некорректным и просто должна быть пара по семантике short/long detailed/simplified full/partial?

2021-07-16 15:35 UTC, martis-git commented on src/pages/card/edit/model.ts
> +});
Тогда не понимаю реализацию разделения))

По сути весь сценарий это "ОСНОВНАЯ ЛОГИКА" + "FALLBACK":

```js
if (cardId)
    redirect_to_card_page(cardId)
else  // fallback
    redirect_to_home_page()
```

Можно было бы с таким успехом даже просто guard повесить какой-нить, который бы вообще не редиректил, если нет cardId (и возможно это даж лучше, я просто хз как в эффекторе это сделать)

2021-07-16 15:38 UTC, martis-git commented on src/features/card/actions/ui/update-changes.tsx
> +};
Нуууу, оке

Но при этом, опять же, не вижу особо проблемы, чтобы скоуп работы с изменениями (сейчас edit, но и create сюда же попадет потом) отделять от обычной логики страницы (тобишь выносить в другой слой)

У нас как раз есть `feature/card-actions`, где хранятся базовые контролы для "редактирования полей" карточки

2021-07-16 15:42 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
> это слишком абстрактно. Имя поэтому и не говорит ни о чем

Лан, убедил))

 Можно во что-то вроде `change-card` т.к. с редактированием полей работает (и в Create/Edit логику подпадает)

2021-07-16 15:46 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
> , а остальное размазано ровным слоем по всему проекту.

Ровным**и** **и предсказуемыми слоями**  - я бы попросил 😎

2021-07-16 15:50 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
> Имхо, оверкилл это вытаскивать не переиспользуемую логику в фичи.

**question:** Ну вот у тебя кнопка "Добавление в корзину". И при этом страница товара, где эта кнопка используется один раз, для добавления основного товара (при желании можно и в скроллбоксы рекоммендаций вставить, но давай пока простой кейс рассмотрим)

И ты же не будешь такую логику держать в странице? Или будешь держать до той поры, как разрастется?

А как же предсказуемость расположения логики и консистентность? А как же то, что даже если фича используется на одной странице, то это не повод ее выносить обратно в страницу?

Или я тебя не так понимаю?

2021-07-16 16:01 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
**question:** Я пытаюсь понять 

1) ты топишь за фабрики из-за каких-то концептуальных соображений *(аля "чтобы логика не сильно размазывалась")*
2) или же чисто из-за **ВОЗМОЖНЫХ** технических ограничений **В БУДУЩЕМ** *(например, что если замонтируем несколько фич на страницу то привязка будет к одному стору)*


Вот щас если откроем страницу - то видим лишь базовую логику, относящуюся чисто к странице

А то, что относится к draft-овой логике, будет в фиче уже)

![image](https://user-images.githubusercontent.com/42924400/125975591-da20f2a1-0f6e-4d9a-aefa-2582a21c0e4a.png)

2021-07-16 16:03 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
Вот да, и я тож такую пару пытаюсь представить

Но у меня в голове и в рабочих проектах обычно всегда было `item`/`details`

2021-07-16 16:05 UTC, martis-git commented on src/features/card/actions/model.ts
> +$draft.reset(resetChanges);
Ну оке, поверю на слово)))))

2021-07-16 16:09 UTC, martis-git commented on src/features/card/actions/model.ts
> +export const $draft = createStore<Draft>(null);
Только если это не resetDraft 😎

2021-07-16 16:16 UTC, martis-git commented
Конфликты поправлю, появились после вливания другого PR

2021-07-16 17:19 UTC, risenforces commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
> Вот да, и я тож такую пару пытаюсь представить
> 
> Но у меня в голове и в рабочих проектах обычно всегда было `item`/`details`

Ну это не оч совсем

2021-07-16 18:33 UTC, OlegBrony commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
`small`/`full`

2021-07-16 23:30 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
> Ну это не оч совсем

Смотря для кого 🤓

2021-07-16 23:31 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
> `small`/`full`

Ну вот да, как будто придется снизойти до типизации по размерам (как я сначала и думал сделать, но показалось что не совсем то, что тут нужно)

2021-07-18 09:54 UTC, sergeysova commented on src/features/card/actions/model.ts
> +export const $draft = createStore<Draft>(null);
Даже если сброс, это будет сброс через домен одним событием.

2021-07-18 09:59 UTC, sergeysova commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
Ну с добавлением в корзину мб и фича.
Но не кнопка редактирования.
С драфтом как раз да, это отличное применение фичи.

по фабрикам валидны оба пункта

2021-07-18 09:59 UTC, sergeysova commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
1. Фабрики позволяют скрыть детали реализации
2. И одновременно инстанциировать раздельные сущности(хоть и оставляют возможность их связать внутри фичи)

2021-07-18 10:02 UTC, sergeysova commented on src/entities/card/model/index.ts
> +);
Да, нормализация через комбинацию зависимых сторов.
Мы не создаем сразу нормализованный стор и пытаемся его обновлять.
Обновляем только исходные сторы, так как удобно, а нормализованный стор автоматом обновится

2021-07-18 10:05 UTC, sergeysova commented on src/pages/card/edit/model.ts
> +});
Ну вот не так. Ты смотришь с точки зрения ифов.
А надо с точки зрения цепочки действий.
Построй цепочку действий по прохождению сценария, и ты сразу заметишь что она разветвится на «фоллбэк».
Лучшая практика это разделять эти цепочки и в эффектор-модели

2021-07-18 10:06 UTC, sergeysova commented on src/features/card/actions/ui/update-changes.tsx
> +};
Я топлю за удаление фичи card-actions. Она неправильно сформулирована.
У тебя будет card-draft, а остальная логика в странице

2021-07-18 13:10 UTC, martis-git commented on src/pages/card/edit/model.ts
> +});
> Лучшая практика это разделять эти цепочки и в эффектор-модели

Нуууу, допустим оке - разделим даж fallback логику на уровне модели

Но как предлагаешь ?)

> То что ты выше предложил, это
> - один сценарий "changesReset" + "paths.home"
> - а другой сценарий "changesSubmitFx" + "paths.card"

2021-07-18 13:23 UTC, martis-git commented on src/features/card/actions/ui/update-changes.tsx
> +};
`question:` Ну т.е. ты от `features/card-draft` предлагаешь оставить по большей части тольк модель саму? (или вообще вынести все в entities такое?)

И при этом кастовать жирные рефлекты что на странице EditPage, что на странице CreatePage?

> Спрашиваю без наброса, просто пока рили кажется, что от такого лишь размажется скоуп ответственности и сами страницы разбухнут (а ты сам побольше моего топил за то, чтобы на страницах не держать лишней логики)

2021-07-20 22:03 UTC, martis-git commented on src/pages/card/edit/model.ts
> +});
@sergeysova Отпиши пож свой варик, иначе придется проигнорить)))

2021-07-20 23:22 UTC, martis-git commented
Такс.... Первый прогон по правкам занял 2+ часов... Остальное видимо завтра уже --___--

2021-07-24 18:22 UTC, martis-git commented on src/pages/paths.ts
> +  cardEdit: (cardId: string) => `/card/${cardId}/edit`,
Похоже out-of-scope, пока никто не отзывается

Вынес в отдельную задачу

https://linear.app/atomix/issue/BOX-166/obsudit-naznachenie-cards-routa

2021-07-24 18:41 UTC, martis-git commented on src/features/card/actions/ui/update-changes.tsx
> +};
Все поправил, но рефлект пока не буду юзать

ИМХО, преждевременная оптимизация, тем более это все в фиче регулируется а не в компоненте страницы

А то что это фича все же - обсудили уже в фиче слайсах

2021-07-24 18:42 UTC, martis-git commented on src/entities/card/model/index.ts
> +);
Пока фигово работает, если не дождусь ответа - видимо тож придется проигнорить))

> Причем "фигово работает" т.е. даже с таким кодом нагроможденным - карточки теперь вообще не грузятся =)
> 
> Возможно я что-то проскипал, но имхо - мы чет к усложнению идем

![image](https://user-images.githubusercontent.com/42924400/126878299-6fc6b5ba-2a69-4d01-9e41-4cf21dca2a48.png)

2021-07-24 18:50 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
Исходя из текущего примера из доки - неясно как это норм реализовать, кроме как запихнуть все в огроменную функцию))


![image](https://user-images.githubusercontent.com/42924400/126878467-86e48234-c23f-4892-932d-5a92fd50d4c2.png)

2021-07-24 18:51 UTC, martis-git commented on src/features/card/actions/model.ts
> +import type { Card } from '@box/api';
Вынес в отдельную задачу, т.к. твои правки сейчас слишком много затрат требуют, сорь

https://linear.app/atomix/issue/BOX-167/dorabotat-modeli-do-best-praktis

2021-07-24 18:52 UTC, martis-git commented on src/entities/card/model/index.ts
> +);
Вынес в отдельную задачу, т.к. твои правки сейчас слишком много затрат требуют, сорь

https://linear.app/atomix/issue/BOX-167/dorabotat-modeli-do-best-praktis

2021-07-24 19:08 UTC, martis-git commented on src/features/card/actions/model.ts
> +});
Поправлю по задаче

https://linear.app/atomix/issue/BOX-167/dorabotat-modeli-do-best-praktis

2021-07-24 19:10 UTC, martis-git commented on src/features/card/actions/model.ts
> +
Поправлю по задаче

https://linear.app/atomix/issue/BOX-167/dorabotat-modeli-do-best-praktis

2021-07-24 19:20 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +type CardType = 'item' | 'details';
Переименовал в `size` поле со значениями `small`/`large`

Позже разобьем на отдельные компоненты скорей всего

2021-07-24 19:22 UTC, martis-git commented on src/pages/card/edit/model.ts
> +});
Тож если и поправлю - то по другой задаче

Пока блокер (но лучше опиши пож свои предложения по пункту более конкретно пож)

https://linear.app/atomix/issue/BOX-167/dorabotat-modeli-do-best-praktis

2021-07-24 19:23 UTC, martis-git commented
@cardbox/core гляньте пож

2021-07-25 09:22 UTC, martis-git commented
@sergeysova Расцепил пока submitChangesFx из draft, чтобы можно было переопределять поведение на уровне страниц без фабрик

> Потом [по задаче](https://linear.app/atomix/issue/BOX-167/dorabotat-modeli-do-best-praktis) поправим *по-нормальному*

https://github.com/cardbox/frontend/pull/43/commits/cc9ab9f605e2de91e3593db5cfc60e0ed71b2fa0

2021-07-25 09:30 UTC, sergeysova approved these changes

2021-07-25 09:30 UTC, sergeysova commented on src/features/card/draft/model.ts
> +// FIXME: simplify to one event?
```suggestion
```

2021-07-25 09:30 UTC, sergeysova commented on src/features/card/draft/model.ts
> +export const $draft = combine<Draft>({
issue: тс может сузить тип T | null до T и ничего тебе не сказать.

suggestion: Никогда не стоит прописывать конкретный тип в дженерике в методы НЕ создающие юниты. Чем больше тс выведет сам, тем лучше.
Достаточно передать сторы в комбайн, остальное само выведется

2021-07-25 09:30 UTC, merged

2021-07-25 09:33 UTC, martis-git commented on src/features/card/draft/model.ts
> +export const $draft = combine<Draft>({
Да, я понимаю)

В идеале вообще бы какой-нить `export type Draft = typeof $draft.getState()` заюзать, но мне нужно было базово расцепить типы для верхнего уровня страниц

2021-07-25 09:33 UTC, martis-git commented on src/features/card/draft/model.ts
> +export const $draft = combine<Draft>({
Сейчас по задаче постараюсь пофиксить, спс

https://linear.app/atomix/issue/BOX-106/stranica-sozdaniya-kartochki

2021-08-04 21:09 UTC, azinit commented on src/features/card/actions/ui/reset-changes.tsx
> +        if (!window.confirm(CANCEL_WARN)) return;
https://linear.app/atomix/issue/BOX-177/vtyanut-i-integrirovat-woly-ui