feature/BOX-139: add link to user(author) page
cardbox/frontend pull request #44
Opened 2021-07-18 12:12 UTC by asvtsv

###  feature/BOX-139-user-links

Добавляет возможность переходить на страницу пользователя

2021-07-18 12:42 UTC, martis-git requested changes
Я бы поправил местами все ж))

А то потом не разгребем тех долг

> Если будут вопросы по тегам, то продолжаем инициативу от @sergeysova 
>
> https://conventionalcomments.org/

2021-07-18 12:42 UTC, martis-git commented on src/app/application.tsx
> +import { viewer } from '@box/api/mock/fixtures';
`issue:` Мы получаем доступ к вьюверу напрямую из фикстур, хотя по идее вообще ничего не должны знать про такую вещь как `mock/fixtures`

`suggestion:` Мб сделать `entities/viewer`, который бы экспортил наружу хук `useViewer`, который бы можно было применять где угодно? (при этом даж не обязательно там пока обвязываться эффектами и прочим - на первое время пойдет тож напрямую импортить фикстуру, но зато это будет на нижнем уровне и в только в одном месте, вышележащие слои вообще не будут знать про это, а будут только хук юзать)

2021-07-18 12:42 UTC, martis-git commented on src/app/application.tsx
> +import { viewer } from '@box/api/mock/fixtures';
Вот можешь глянуть, тут пример есть

https://feature-sliced.design/docs/guides/examples/viewer/#model

2021-07-18 12:42 UTC, martis-git commented on src/app/application.tsx
> +        <Searchbar user={viewer} />
`suggestion:` Предлагаю не прокидывать вьювера в фичу сверху, а получать напрямую внутри фичи

2021-07-18 12:42 UTC, martis-git commented on src/app/application.tsx
> +        <Searchbar user={viewer} />
И вот еще пример использования контекста вьювера внутри фичи
https://feature-sliced.design/docs/guides/examples/viewer/#ui-1

2021-07-18 12:42 UTC, martis-git commented on src/app/application.tsx
> +        <Searchbar user={viewer} />
См. те же признаки)

![image](https://user-images.githubusercontent.com/42924400/126067179-f3da0ccd-d2d4-4d31-8107-7f2053dfa5a1.png)

2021-07-18 12:42 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +    <UserLink href={`/u/${author.username}`}>
`issue:` Слой entities знает про роутинг страницы, хотя это не его скоуп ответственности

`suggestion:` Предлагаю, чтобы роут поступал через пропсы, а сам урл определялся на уровне страницы использования

2021-07-18 12:42 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +    <UserLink href={`/u/${author.username}`}>
См. те же признаки)

![image](https://user-images.githubusercontent.com/42924400/126067179-f3da0ccd-d2d4-4d31-8107-7f2053dfa5a1.png)

2021-07-18 12:42 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +      <Text type={TextType.small}>EffectorMaster</Text>
`suggestion:` Чтобы не хардкодить каждый раз логику роута, предлагаю заиспользовать это из paths (см и другие примеры в коде)

> Особенно когда вынесешь на уровень страниц, проблем с импортами не будет как раз

```ts
import { paths } from "../paths";
...
<CardPreview href={paths.user(card.author.username)} />
```

2021-07-18 12:42 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
> +`;
`issue:` При переходе по нативной ссылке, внутренний роутинг react-router  и его оптимизации пойдут лесом, что не оч хорошо)
(т.е. страницы будут снова полностью перерендериваться со всеми запросами

`suggestion:` Поскольку это обращение к внутренней страницы системы, предлагаю заюзать `Link` из react-router-dom

> В этом же файле кста так же стилизуется TitleLink чуть выше

```diff
+ import { Link } from "react-router-dom";
+ const UserLink = styled(Link)`
```

2021-07-18 12:42 UTC, martis-git commented on src/entities/user/organisms/user-preview.tsx
> +      <UserLink href={`/u/${username}`}>
`suggestion:` Снова лучше бы вынести на уровень страниц

2021-07-18 12:42 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +import { User } from '@box/api';
`nitpick` Импортировать бы как тип для оптимизаций)

```diff
+ import type { User } from '@box/api';
```

2021-07-18 12:42 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
> +          <UserLink href={`/u/${user.username}`}>
`suggestion`: Again, move to pages logic)

2021-07-18 12:42 UTC, martis-git commented on src/pages/comments/comments.tsx
> +          author={{ id: '1', username: 'LangCreator' }}
`thoughts`: Эх, подтянуть бы потом мок данные и к этой странице)

2021-07-22 14:50 UTC, martis-git approved these changes
В принципе ОК, но надеюсь ты и дальше расцепишь features-pages связи))

Если остались вопросы, можем созвониться вечерком

2021-07-22 14:50 UTC, martis-git commented on src/entities/card/organisms/card-list.tsx
> +          userHref={getUserHref?.(card)}
`thoughts:` Блен)

Похоже **потом** надо устранить card-list как таковой, а то слишком много бойлерплейта, а профита никакого толком

2021-07-22 14:50 UTC, martis-git commented on src/entities/card/organisms/card-preview.tsx
>        <Text type={TextType.small}>EffectorMaster</Text>
`question:` Кста только щас заметил - а поч здесь не `author.username`?

2021-07-22 14:50 UTC, martis-git commented on src/entities/user/organisms/user-preview.tsx
> +      <UserLink to={paths.user(username)}>
`issue:` Here we go again)

entity внезапно знает про pages логику (это как фича бы импортила ресурсы/модель страницы)

`suggestion:` Как и с карточкой - я бы вынес на уровень страницы через пропсы (пока пусть дриллится через user-list, но потом удалим скорей всего)

2021-07-22 14:50 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
>              </LoginBlock>
`issue:` Снова  нижний слой знает про слой страниц

`suggestion:` Предлагаю тут не просто вынести href в пропсы, а в целом добавить возможность через пропсо пределить зону "аватарка пользователя" (допустим, если в будущем понадобиться вместо аватарки вставить что-то другое)

Если же search-bar используется много раз на странице и это приводит к бойлерплейту - то это еще и хороший повод вынести в виджеты (как описано в примере ниже по ссылке)

`tip:` Можешь глянуть то, как это [в виджетах](https://feature-sliced.design/docs/reference/layers/widgets/#%D1%85%D0%B5%D0%B4%D0%B5%D1%80-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F) реализуется

Здесь тоже подойдет, если даже на уровне фичи сделаешь

2021-07-22 14:50 UTC, martis-git commented on src/pages/comments/comments.tsx
> +const UserLink = styled(Link)``;
`question:` А зач оборачиваешь в стайлед если нет стилей?)

2021-07-22 14:50 UTC, martis-git commented on src/pages/card/index.tsx
> +            <UserCard user={user} href={paths.user(card?.author.username)} />
`praise:` Во, тут ты правильно прям сделал)

Как раз вынес все на уровень страницы

2021-07-22 14:50 UTC, martis-git commented on src/pages/user/index.tsx
> +                getUserHref={(card) => paths.user(card.author.username)}
`praise:` Во, и тут тоже хорошо сделал)

`thoughts:` Потом правда нафиг сожжем этот card-list - пока от него больше вреда чем пользы 😄

2021-07-22 14:50 UTC, martis-git commented on src/features/search-bar/organisms/search-bar.tsx
>              </LoginBlock>
`thoughts:` Глянул, пока это используется только в одной точке приложения (на самом верху)

Можно пока оставить в виде фичи, но любым удобным тебе способом - надо расцепить связь между `features > import  > pages`

- Либо через пропс передавай урл (ОК, но не оч)
- Либо через пропс передавай весь ReactNode, без завязки на то, что там всегда должен быть Avatar (вот это как по мне получше - можешь глянуть тот же пример с виджетами, поймешь о чем я 🚀 )

2021-07-22 19:12 UTC, martis-git submitted a review, later dismissed
🔥

2021-07-22 19:13 UTC, martis-git commented
@cardbox/core киньте пож еще один аппрув (рефакторинг и прочие некритичные правки в след PR, чтоб не затормаживать)

2021-07-22 19:18 UTC, martis-git commented on src/pages/comments/comments.tsx
> +const UserLink = styled(Link)``;
Лул)

2021-07-22 19:22 UTC, martis-git commented on src/pages/comments/comments.tsx
> +const UserLink = styled(Link)``;
@asvtsv чет в прошлый раз загрузки пользователя не было, теперь это)))

Спасибо @OlegBrony что склонировал хоть, но я чет думал, что в этом то плане можно не проверять уж

2021-07-22 19:23 UTC, martis-git commented on src/pages/comments/comments.tsx
> +const UserLink = styled(Link)``;
Видимо CI-чек на `run without crushing` придется ввести 🤷

2021-07-22 20:29 UTC, martis-git commented
@asvtsv 🤷

1. Не грузится страница вьювера (и при клике, и при прямом переходе)

    ![image](https://user-images.githubusercontent.com/42924400/126705060-88a9af1d-e033-43b3-b14b-2db3aa52790b.png)

2. Юзернейм почему-то пропадает в карточках

   ![image](https://user-images.githubusercontent.com/42924400/126705065-1b5fda1b-34ad-4ec3-bbf6-c22efb73bc60.png)

3. Тайтл user-preview не hover'ится при наведении и имеет странное подчеркивание (тож базовый кейс и надо бы обработать)

    ![image](https://user-images.githubusercontent.com/42924400/126705117-77547b50-93eb-4984-bc67-5b415d2e7c33.png)

2021-07-22 20:50 UTC, OlegBrony approved these changes

2021-07-22 20:51 UTC, OlegBrony commented
хз, стоит ли чего-то мой аппрув, но поставлю)

2021-07-22 21:43 UTC, OlegBrony commented on src/pages/comments/comments.tsx
> +const UserLink = styled(Link)``;
Это моя работа 😎

2021-07-22 22:35 UTC, martis-git approved these changes
чери-пики и в мастер)))

Надеюсь найдем время на рефакторинг уже наконец 

~~(спойлер: никогда)~~

2021-07-22 22:36 UTC, martis-git commented
@OlegBrony давай по новой)))

2021-07-23 07:21 UTC, OlegBrony approved these changes

2021-07-23 07:23 UTC, merged