Replaces some repeatable css colors with custom props
cardbox/frontend pull request #48
Opened 2021-08-06 19:54 UTC by OlegBrony

также чучуть поправил commitizen.

2021-08-06 20:12 UTC, azinit requested changes
В целом оке, но вот с unknown непонятки

2021-08-06 20:12 UTC, azinit commented on .cz-config.js
> +  { value: "wip",      name: "wip",      description: "Work in progress" },
[`thoughts:`](https://conventionalcomments.org/) Ухх, интересно кто придумал изначально так форматить))))

2021-08-06 20:12 UTC, azinit commented on src/app/application.tsx
> +    --unknown-8: #f4f2f7;
[`issue:`](https://conventionalcomments.org/) Понимаю, что названия цветов в фигме нет, но тем не менее - с таким сложно потом работать будет)

[`suggestion:`](https://conventionalcomments.org/) Кмк, можно подобрать такие названия, чтобы по смыслу не нарушалось ничего
*(если не удается сделать цвета наподобие `primary` / `secondary` / `danger` / ... - то можно хотя бы как в tailwind-css: red-400, yellow-200, ...)*

2021-08-06 20:12 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +    background: var(${theme.palette.bnw0});
[`question:`](https://conventionalcomments.org/) А не подскажешь - как bnw0 расшифровывается?

2021-08-06 20:12 UTC, azinit commented on src/lib/theme.ts
> +  ],
[`praise:`](https://conventionalcomments.org/) Интересное решение)

Хз насколько с foliage потом будет стыковаться - но выглядит прикольно

(@sergeysova можешь тоже глянуть ради интереса)

2021-08-06 20:12 UTC, azinit commented on src/pages/card/view/index.tsx
> +  color: var(${theme.palette.notice500});
[`thoughts:`](https://conventionalcomments.org/) Есть серьезные опасения , что если будем вслепую брать названия из фигмы, то с таким неймингом потом только страдать будем...

Вот в каком месте это `notice500` - я прост вообще не пойму)

Ладно бы какой-нить `danger`/`caution` - но не так же...

2021-08-06 20:12 UTC, azinit commented on src/ui/organisms/user-card.tsx
> +  const username = `${user.firstName} ${user.lastName}`;
[`thoughts:`](https://conventionalcomments.org/) Потом бы в `entities/user/lib [getters]` вынести)

Но уже не твоя задача - если только захочешь сам

2021-08-06 20:12 UTC, azinit commented on src/lib/theme.ts
> +  bnw200: '--bnw200',
[`thoughts:`](https://conventionalcomments.org/) Поправь еще пож в[ предыдущем PR](https://github.com/cardbox/frontend/pull/47) - чтобы влить можно было)

2021-08-06 20:21 UTC, OlegBrony commented on src/app/application.tsx
> +    --unknown-8: #f4f2f7;
по поводу нейминга в целом: я котегорически против новых имён - либо мы просто используем те, что написал дизайнер, либо переписываем на более логичные и тут и в фигме. потом путаница будет, если мы будем на разных языках общаться.

2021-08-06 20:21 UTC, OlegBrony commented on src/entities/card/organisms/card-preview.tsx
> +    background: var(${theme.palette.bnw0});
не подскажу)

2021-08-06 20:23 UTC, OlegBrony commented on src/lib/theme.ts
> +  ],
нагло [скопипиздил](https://material-ui.com/customization/default-theme/))

2021-08-06 20:23 UTC, OlegBrony commented on src/pages/card/view/index.tsx
> +  color: var(${theme.palette.notice500});
по поводу нейминга в целом: я котегорически против новых имён - либо мы просто используем те, что написал дизайнер, либо переписываем на более логичные и тут и в фигме. потом путаница будет, если мы будем на разных языках общаться.

2021-08-06 20:24 UTC, OlegBrony commented on src/lib/theme.ts
> +  bnw200: '--bnw200',
это вливание как раз в ту ветку, не в мастер.

2021-08-06 20:25 UTC, azinit commented on src/pages/card/view/index.tsx
> +  color: var(${theme.palette.notice500});
Ну вот надо бы

Хотя вродь у @sergeysova тож свое мнение на этот счет было

2021-08-06 20:29 UTC, OlegBrony commented on src/app/application.tsx
> +    --unknown-8: #f4f2f7;
по смыслу там нужно сделать гораздо больше - _создать_ палитру. я её не создавал - я только создал переиспользуемые цвета, но именно палитры нет. нет системы цветов.

2021-08-06 20:31 UTC, OlegBrony commented on src/ui/organisms/user-card.tsx
> +  const username = `${user.firstName} ${user.lastName}`;
у меня просто глаз за это зацепился, немношк подёргался и я поправил. чучуть

2021-08-06 20:39 UTC, azinit commented on src/app/application.tsx
> +    --unknown-8: #f4f2f7;
Ну поправь сейчас хотя бы как есть
А я тикет заведу, чтобы мы с палитрой обкашляли вопрос

2021-08-06 20:39 UTC, azinit commented on src/app/application.tsx
> +    --unknown-8: #f4f2f7;
`unknown` даже как временное решение не айс)

Лучше хотя бы в своей интерпретации как-то оставить, пусть и с дизайном не засинкано

2021-08-06 20:40 UTC, azinit commented on src/app/application.tsx
> +    --unknown-8: #f4f2f7;
Закинул в тикетос отдельный

https://linear.app/atomix/issue/BOX-183/obsudit-dizajn-palitru-i-nejming

2021-08-09 08:17 UTC, OlegBrony commented on src/app/application.tsx
> +    --unknown-8: #f4f2f7;
опять абстрактные требования... что ты конкретно хочешь? чтоб я их убрал и вернул в css? ок. я назвал это unknown, как раз чтоб в долгий ящик это не клали.

2021-08-09 08:17 UTC, OlegBrony commented on src/app/application.tsx
> +    --unknown-8: #f4f2f7;
я эту группу цветов никак обозвать не могу.

2021-08-09 08:43 UTC, antonmazhuto commented on src/pages/card/view/index.tsx
> +  color: var(${theme.palette.notice500});
лично я считаю, что в целом все равно, но чтобы не путаться в будущем, думаю можно взять более осмысленные, так как в макетах, наверно, названия абстрактные

2021-08-09 08:48 UTC, OlegBrony commented on src/pages/card/view/index.tsx
> +  color: var(${theme.palette.notice500});
ну пусть они осмысленными будут везде

2021-08-13 20:24 UTC, merged