Box 151
cardbox/frontend pull request #49
Opened 2021-08-07 11:50 UTC by antonmazhuto

https://linear.app/atomix/issue/BOX-151/dorabotat-searchresults-and-card-logiku  
  - [ ] добавил заглушку на cards и users, если пришли пустые данные

2021-08-07 13:06 UTC, azinit reviewed
Ок, но пару моментов поправить бы)

2021-08-07 13:06 UTC, azinit commented
@antonmazhuto а ты остальные моменты по задачи другими PR закрыть планируешь?

2021-08-07 15:38 UTC, antonmazhuto commented on src/entities/card/organisms/card-list.tsx
> +import { useKeyboardFocus } from "@box/lib/use-keyboard-focus";
да, тут согласен. У меня заменяются на двойные(

2021-08-07 15:39 UTC, antonmazhuto commented on src/ui/atoms/empty.tsx
> +import React, { FC } from 'react';
fixed

2021-08-07 15:41 UTC, azinit commented on src/entities/card/organisms/card-list.tsx
> +import { useKeyboardFocus } from "@box/lib/use-keyboard-focus";
Согласуй с IDE eslint/prettier)

2021-08-07 15:41 UTC, azinit commented on src/entities/card/organisms/card-list.tsx
> +import { useKeyboardFocus } from "@box/lib/use-keyboard-focus";
У тебя он похоже не видит

2021-08-07 15:41 UTC, antonmazhuto commented on src/ui/atoms/empty.tsx
> +export const Empty: FC<EmptySearchProps> = ({ text }) => {
fixed

2021-08-07 15:42 UTC, azinit commented on src/ui/icons/empty.svg
> +<svg width="130" height="80" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient x1="52.348%" y1="74.611%" x2="52.348%" y2="-17.635%" id="a"><stop stop-color="#DEDEDE" stop-opacity="0" offset="0
Тоже убрать бы тогда (зарезолвь как пофиксишь)

2021-08-07 15:42 UTC, antonmazhuto commented on src/entities/user/organisms/user-preview-list.tsx
> +  }
пока хз

2021-08-07 15:48 UTC, azinit commented on src/entities/user/organisms/user-preview-list.tsx
> +  }
Ну мне тож норм в такой реализации оставить пока))

2021-08-07 16:10 UTC, antonmazhuto commented on src/ui/atoms/empty.tsx
> +  return (
пока оставил так, потом поменяю как будет дизайн

2021-08-07 16:10 UTC, antonmazhuto commented on src/ui/icons/empty.svg
> +<svg width="130" height="80" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient x1="52.348%" y1="74.611%" x2="52.348%" y2="-17.635%" id="a"><stop stop-color="#DEDEDE" stop-opacity="0" offset="0
deleted

2021-08-07 17:05 UTC, azinit commented
@antonmazhuto в задачке бы тож не забывать чекбоксы закрывать)
Чтоб понимание было потом

![image](https://user-images.githubusercontent.com/42924400/128608226-7d09b715-72bb-4453-bf17-80be450f18fb.png)

2021-08-07 17:05 UTC, azinit commented
@antonmazhuto А зач переименовал? Обычно же наоборот с task-key в начале PR пишем тайтлы)

![image](https://user-images.githubusercontent.com/42924400/128608242-c3904516-ebcc-48db-8e4f-56a93b906894.png)

2021-08-07 18:26 UTC, azinit approved these changes
Не хватает еще поиска по bio для юзеров - но щас один хрен, с новой АПИхой это и не пригодится)

2021-08-07 18:26 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +import React, { MouseEventHandler, forwardRef, useRef } from 'react';
[`nitpick(non-blocking):`](https://conventionalcomments.org/) Некритично, но импортировать бы тип динамически (`import(react).MouseEventHandler`) или через отдельный импорт типов (`import type {MouseEventHandler} from "react"`)

2021-08-07 18:26 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> -
[`question:`](https://conventionalcomments.org/) В итоге оверхедом оказалось?) [2]

2021-08-07 18:26 UTC, azinit commented on src/ui/atoms/empty.tsx
> +  return (
Оке))

2021-08-07 18:26 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +        )}
[`issue(non-blocking, DRY):`](https://conventionalcomments.org/) Смотри, если я не ошибаюсь такая же UI-логика дублируется в user-preview

(а она достаточно нетривиальна и занимает много места)

[`suggestion(non-blocking, DRY):`](https://conventionalcomments.org/) Как предложение - вынести в отдельный UIKit-компонент 

`<HighilightText />`, где один пропс бы принимал исходный text и поисковую фразу

2021-08-08 13:33 UTC, antonmazhuto commented on src/entities/card/organisms/card-list.tsx
> -import { useKeyboardFocus } from '@box/lib/use-keyboard-focus';
да

2021-08-08 13:35 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +import React, { MouseEventHandler, forwardRef, useRef } from 'react';
fixed

2021-08-08 13:35 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> -
Я думаю это пока лишнее. Упростил как мог. Если не прав, поправь меня))

2021-08-08 18:54 UTC, azinit requested changes
Сорь, пока слишком много вопросов)

2021-08-08 18:54 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +  const query = useSearchQuery();
[`thoughts:`](https://conventionalcomments.org/) Эх, вынести бы потом эту search-логику из entities))

Но лан, пока в тикет вынес отдельный, пусть будет как будет

2021-08-08 18:54 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +              <HighlightText query={query} entity={title} />
[`nitpick:`](https://conventionalcomments.org/)

Мб так?

```suggestion
              <HighlightText query={query} text={title} />
```

2021-08-08 18:54 UTC, azinit commented on src/entities/user/organisms/user-preview.tsx
> -          ))}
[`praise:`](https://conventionalcomments.org/) Вооо, именно это и имел в виду, круть!)

2021-08-08 18:54 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +          </TitleLink>
[`issue:`](https://conventionalcomments.org/) В user-preview у тебя такой же кейс, но там у тебя нет проверки на query

[`issue(non-blocking):`](https://conventionalcomments.org/) Выглядит громоздко тернарник подобный

--- 
[`suggestion:`](https://conventionalcomments.org/) Вижу два варианта:

1. Адаптировать HighlightedText так, чтобы обрабатывался кейс, когда query пустой/необязательный (и там бы уже возвращался title без покраски и маппинга по токенам)

```ts
// .../highlighted-text.ts

// `props .` тут лишь для наглядности
if (props.query === '') return props.text;

const data = getQueryData(props.query, props.text);
return (
   {data.map(...)}
)
```

2. Добавить эту логику и в user-preview, чтобы тоже такой сценарий проверялся

> Я лично больше за первый вариант

2021-08-08 18:54 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> -  };
[`thoughts:`](https://conventionalcomments.org/) Так и не пригодилось как понял)

> Вынес в тикет
> https://linear.app/atomix/issue/BOX-189/prorabotat-a11y

2021-08-08 18:54 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> -  };
[`question:`](https://conventionalcomments.org/) А не подскажешь - старая реализация с mouse-select осталась? А то не вижу, как ты тут ее отрефакторил

2021-08-08 18:54 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +import type { MouseEventHandler } from 'react';
[`question:`](https://conventionalcomments.org/) Сорян, но чет я не вижу где теперь MouseEventHandler юзается))

Точно ли этот тип нужен тут?

2021-08-08 18:54 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +import type { MouseEventHandler } from 'react';
[`suggestion:`](https://conventionalcomments.org/) И даже если да - то сорь, я тупанул - до него можно было через `React.MouseEventHandler` достучаться

2021-08-08 20:15 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +        )}
fixed

2021-08-08 20:15 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +  const query = useSearchQuery();
ok

2021-08-08 20:25 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +              <HighlightText query={query} entity={title} />
done

2021-08-08 20:25 UTC, antonmazhuto commented on src/entities/user/organisms/user-preview.tsx
> -          ))}
- [ ]

2021-08-08 20:32 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +          </TitleLink>
done

2021-08-08 20:33 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +import type { MouseEventHandler } from 'react';
fixed

2021-08-08 20:50 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> -  };
refactor useMouseSelection hook

2021-08-08 21:20 UTC, azinit approved these changes
🚀

2021-08-08 21:27 UTC, Kater-auf-Dach approved these changes

2021-08-08 21:28 UTC, merged