fix: added delete button show condition
cardbox/frontend pull request #50
Opened 2021-08-07 16:49 UTC by antonmazhuto

- [ ] добавил условие показа кнопки "Delete card"

2021-08-07 16:51 UTC, antonmazhuto commented on src/pages/card/view/index.tsx
> +              {card && viewer.id === card.author.id && (
Сразу говорю, что хз насчет корректности данного решения, но с текущими данными и в текущей ситуации - думаю норм

2021-08-07 18:36 UTC, azinit requested changes
Проверка норм, но не хватает самой имплементации удаления карточки)))

~~просто добавь попапчик с подтверждением и в случае успеха - отправляй запрос на mock-api~~

~~+ обработай редирект~~

2021-08-08 14:36 UTC, azinit approved these changes
В целом гуд, но есть что улучшить)

2021-08-08 14:36 UTC, azinit commented on src/pages/card/view/index.tsx
> +                  to="#delete"
[`issue:`](https://conventionalcomments.org/) У нас же по сути тут кнопка удаления рили как кнопка работает)

И без редиректов

[`suggestion:`](https://conventionalcomments.org/) Мб тогда убрать href и имплементировать как кнопку?

2021-08-08 14:36 UTC, azinit commented on src/pages/card/view/model.ts
> +  // FIXME: push user to profile
[`nitpick:`](https://conventionalcomments.org/) Мб так?

```suggestion
  // FIXME: push later to card.author page
```

2021-08-08 14:36 UTC, azinit commented on src/pages/card/view/index.tsx
> +              {card && viewer.id === card.authorId && (
[`suggestion(non-blocking):`](https://conventionalcomments.org/) Некритично, но мб вынести в `entities/viewer/lib` хелпер `isViewerById` ?

```ts
// entities/viewer/lib.ts
export function isViewerById(userId: string): boolean {
     // А внутри будет доступ к объекту вьювера

// pages/card/view/index.ts
{card && isViewerById(card.authorId) && (
```

2021-08-08 15:07 UTC, antonmazhuto commented on src/pages/card/view/index.tsx
> +                  to="#delete"
fixed

2021-08-08 15:08 UTC, antonmazhuto commented on src/pages/card/view/model.ts
> +  // FIXME: push user to profile
согласен

2021-08-08 15:16 UTC, antonmazhuto commented on src/pages/card/view/index.tsx
> +              {card && viewer.id === card.authorId && (
fixed

2021-08-08 18:32 UTC, azinit approved these changes
Надеюсь работает, на клонирование нет времень)

2021-08-08 18:39 UTC, sergeysova approved these changes

2021-08-08 18:41 UTC, merged