Feature/box 207 Update styles according to design
cardbox/frontend pull request #65
Opened 2021-09-13 20:50 UTC by Kater-auf-Dach

- Updated styles and markup
  - Icon changed from img to svg via razzle plugin
  - Changed buttons theme
  - Renew theme shadows

2021-09-13 21:28 UTC, azinit requested changes
Все круто, но мешает поставить аппрув момент с navModel)

Надо бы разобраться с ним

2021-09-13 21:28 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +          icon={<IconDeckCheck />}
[`nitpick`](https://conventionalcomments.org/#labels) А через такие свгшки же все равно по идее можно передавать тайтл, не?

`<IconDeckCheck title="..." />`

2021-09-13 21:28 UTC, azinit commented on src/entities/user/ui/user-card.tsx
> +  box-shadow: ${theme.shadows[1]};
[`praise:`](https://conventionalcomments.org/#labels) 🔥 🔥

2021-09-13 21:28 UTC, azinit commented on src/features/card/draft/ui/atoms/tag-input.tsx
> +    // FIXME: Цвет не совпадает с темой, инлайн не работает из-за каскада
[`suggestion:`](https://conventionalcomments.org/#labels) Хм, а разве не хватит обернуть в Button в styled и задать нужный цвет?

2021-09-13 21:28 UTC, azinit commented on src/pages/card/view/page.tsx
> +                <ButtonCard
[`issue(critical)`](https://conventionalcomments.org/#labels) Не очень, что приходится вытягивать аж navModel чтобы просто совершить переход по ссылке

\+ Не знаю как конкретно это устроено внутри, но кажется эта модель не учитывает и react-router, т.е. будут лишние ререндеры (хотя с SSR может быть своя специфика)

[`suggestion`](https://conventionalcomments.org/#labels) Мб имеет смысл попробовать отказаться от onClick и хендлеров и попробовать как-то обернуть `<Link/>` из реакт-роутера над кнопкой?

```tsx
<Link to={paths.edit(id)}>
   <Button ...>
     ...
   </Button>
</Link>
```

[`thoughts:`](https://conventionalcomments.org/#labels) Да, это будет немного рушить семантику, зато кажется достаточно простым решением здесь для интерактивности

2021-09-13 21:28 UTC, azinit commented on src/pages/card/view/page.tsx
> +                <ButtonCard
@sergeysova @dmi-ch @asvtsv @antonmazhuto @OlegBrony @Irinaristova Что думаете?)

2021-09-13 21:28 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +        icon={<IconDeckArrow />}
[`praise:`](https://conventionalcomments.org/#labels) Круто, что заиспользовал иконку так, как это задумывалось при разработке компонента кнопки)

2021-09-13 21:28 UTC, azinit commented on src/pages/home/page.tsx
> +  }
[`thoughts:`](https://conventionalcomments.org/#labels) Таки решил уже адаптив в этот PR потихоньку втягивать?)

2021-09-13 21:28 UTC, azinit commented on src/pages/home/page.tsx
> +        }
[`praise:`](https://conventionalcomments.org/#labels) Круть, что получилось не перефигачивать button ради этого)

2021-09-13 21:28 UTC, azinit commented on src/ui/atoms/button.tsx
>    }
[`question`](https://conventionalcomments.org/#labels) А не можем сделать акцент на currentColor? У нас же не всегда fill подраузмевает быть заполненным, свгшки оч разные же бывают

2021-09-13 21:28 UTC, azinit commented on src/ui/atoms/button.tsx
> +  }
[`question:`](https://conventionalcomments.org/#labels) А тут можешь тоже пож объяснить?

У нас же вроде это достигается `outlined + primary` не?

2021-09-13 21:28 UTC, azinit commented on src/ui/atoms/button.tsx
> +  }
[`issue:`](https://conventionalcomments.org/#labels) Не хочется прост усложнять API кнопки и так не самое простое

2021-09-13 21:28 UTC, azinit commented on src/ui/icons/index.ts
> +export { ReactComponent as IconUserLogoDefault } from './default_userlogo.svg';
[`suggestion(non-blocking):`](https://conventionalcomments.org/#labels) Было бы круто вообще реэкспортить из иконок все под неймспейсом `Icon`, чтобы не цеплять контекст в названии у каждой иконки

**Или хотя бы чтоб было четко понимание - что мы не просто UIKit импортим, а конкретно его иконки**

2021-09-13 21:28 UTC, azinit commented on src/ui/molecules/chip.tsx
> +        <IconClose />
[`suggestion(non-blocking):`](https://conventionalcomments.org/#labels) Мб занесем `title='Remove tag'`?

2021-09-13 21:28 UTC, azinit commented on typings/index.d.ts
>  }
[`praise:`](https://conventionalcomments.org/#labels) Балдеж!

2021-09-13 21:36 UTC, Kater-auf-Dach commented on razzle.config.js
> +              'You can fix this via running `$ ./scripts/create-certs.sh`, but before read Development section in README.md',
Это, видимо, линтер отработал, так как спецом не правил

2021-09-13 21:37 UTC, Kater-auf-Dach commented on src/pages/card/view/page.tsx
> +                <ButtonCard
Этот момент меня тоже смущает, поэтому хотелось обсудить

2021-09-13 21:38 UTC, Kater-auf-Dach commented on src/entities/user/ui/user-card.tsx
> +  box-shadow: ${theme.shadows[1]};
Это не мое изобретение, я лишь применил его везде, поправив под макет)

2021-09-13 21:41 UTC, Kater-auf-Dach commented on src/entities/card/organisms/card-preview.tsx
> +          icon={<IconDeckCheck />}
Согласен, упустил из виду

2021-09-13 21:47 UTC, Kater-auf-Dach commented on src/features/card/draft/ui/atoms/tag-input.tsx
> +    // FIXME: Цвет не совпадает с темой, инлайн не работает из-за каскада
Можно. Что-то типа
```js
const SubmitButton = styled(Button)`
  & svg {
    fill: var(${theme.palette.bnw600});
  }
`;
```
 Но хотелось еще подумать - так как в редакторе все кнопки такие, и, судя по макету, только в нем

2021-09-14 07:40 UTC, Kater-auf-Dach commented on src/ui/atoms/button.tsx
> +  }
У нас есть два вида `outline` кнопок: 
- дефолтный бордер + текст цвета темы 
- и бордер и текст цвета темы
`outlined + primary` дает второй вариант, поэтому добавил дополнительное свойство, чтобы бордер и текст не зависели друг от друга

2021-09-14 07:47 UTC, Kater-auf-Dach commented on src/pages/home/page.tsx
> +  }
Ну я бы не назвал это добавлением адаптива. Просто на макете данный текст короче заголовка. И тут два варианта - либо <br />, либо ограничение ширины.

2021-09-14 07:51 UTC, Kater-auf-Dach commented on src/ui/atoms/button.tsx
>    }
Можем

2021-09-20 18:04 UTC, azinit approved these changes

2021-09-20 18:04 UTC, azinit commented on src/ui/atoms/button.tsx
> +  }
[`question:`](https://conventionalcomments.org/#labels) А можно примерами кнопок пож?)

Ты как никак с макетами больше меня времени провел, я уже забыл многое

[`thoughts:`](https://conventionalcomments.org/#labels) Но на крайний - хотя бы FIXME поставить бы, т.к. чет кажется что это скорее костыль

(могу ошибаться, поправь меня тогда пож визуальными примерами если несложн)

2021-09-21 22:57 UTC, Kater-auf-Dach commented on src/ui/atoms/button.tsx
> +  }
например иконки в карточках в зависимости от их состояния
или кнопки создания/редактирования/удаления карточки

2021-09-21 23:09 UTC, Kater-auf-Dach commented on src/features/card/draft/ui/atoms/tag-input.tsx
> +`;
ну внутри `svg` и используется `currentColor`
а тут придется бороться со специфичностью кнопок, которую повышают дата-атрибуты

2021-09-22 05:52 UTC, sergeysova approved these changes

2021-09-22 06:56 UTC, antonmazhuto approved these changes

2021-09-22 08:48 UTC, azinit commented on src/features/card/draft/ui/atoms/tag-input.tsx
> +`;
Не понял чем это мешает, но лан - некритично)

2021-09-22 09:03 UTC, azinit approved these changes

2021-09-22 09:03 UTC, merged