BOX-156/popravit-otobrazhenie-cardemptycase-404
cardbox/frontend pull request #66
Opened 2021-09-22 07:58 UTC by antonmazhuto

### Branch name
  
  - [ ] Your branch should be prefixed with `feature/` or `fix/` or `chore/` or `refactor/` or `tests/`
  - [ ] Add issue identifier
  - [ ] Add 3-5 words of description separated with `-`
  
  Example:
  
  ```
  feature/BOX-12-add-login-form
  fix/BOX-8-loading-panel-on-first-load
  chore/BOX-22-add-release-drafter
  ```
  
  ### PullRequest
  
  - [ ] This PullRequest implements new feature, fix bug, or some other changes
  - [ ] If PR is not ready to review mark it as Draft
  - [ ] All commits in this PR should be created by `yarn commit` by [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/)
  - [ ] Title of the PullRequest should have issue(s) identifier(s) ("BOX-123 Example title of PR")

2021-09-22 08:49 UTC, azinit requested changes
Тебя ничего не смутило? 😄 

![image](https://user-images.githubusercontent.com/42924400/134312774-fc80daf6-d3af-411b-b65a-9b18de8e005c.png)

2021-09-22 09:00 UTC, azinit requested changes
Нужны доработки))

2021-09-22 09:00 UTC, azinit commented on src/ui/atoms/empty.tsx
>  };
[`issue(critical):`](https://conventionalcomments.org/#labels) Мы наделяем обычный UIKit лишней логикой)

Во-первых - конкретная кнопка, зашитая в заглушку
Во-вторых - редирект на конкретную страницу

[`suggestion(critical)`](https://conventionalcomments.org/#labels) Кмк, тут лучше давать возможность прокидывать нужный ReactNode внутрь заглушки (через children или любой другой пропс - можно глянуть как у antd сделано)

https://ant.design/components/empty/

2021-09-22 09:00 UTC, azinit commented on src/ui/atoms/empty.tsx
>  };
[`thoughts:`](https://conventionalcomments.org/#labels) Если и зашивать кнопку (которая по факту ссылка), кмк, то хотя бы дать возможность снаружи задавать инфу для нее

Но чет пока кажется - что в большинстве кейсов проще будет самим ReactNode прокидывать

2021-09-22 09:00 UTC, azinit commented on src/pages/card/view/page.tsx
> +
[`question:`](https://conventionalcomments.org/#labels) А морганий заглушки во время загрузки не будет? Ты чекал?)

2021-09-22 09:00 UTC, azinit commented on src/pages/card/view/page.tsx
> +  if (!card && !isLoading) {
[`nitpick(critical):`](https://conventionalcomments.org/#labels) В задаче видимо тож не заметил - но CardEditPage тоже обработать надо корректней для 404 случая)))

![image](https://user-images.githubusercontent.com/42924400/134313979-30827515-4e9c-41d1-93d5-e8bb424f1b3d.png)

2021-09-22 09:00 UTC, azinit commented on src/pages/card/view/page.tsx
> +    );
[`suggestion(non-blocking):`](https://conventionalcomments.org/#labels) Некритично, но я бы для заглушке повыше отступ сделал от вверха страницы

Потому что пока оч сыро выглядит текст, почти прилипленный к хедеру


[`praise:`](https://conventionalcomments.org/#labels) Но круто, что постарался обратить внимание на примеры с antd!

https://ant.design/components/result/#components-result-demo-404

2021-09-22 09:02 UTC, antonmazhuto commented on src/ui/atoms/empty.tsx
>  };
тут согласен, поправлю

2021-09-22 09:03 UTC, antonmazhuto commented on src/pages/card/view/page.tsx
> +
Я поэтому и поставил !isLoading. Или не в этом вопрос?

2021-09-22 09:18 UTC, azinit commented on src/pages/card/view/page.tsx
> +
Вопрос был в том - чекал ли ты отдельно , что нет моргания)

потому что раньше такая проблема была, даже с флагом `!isLoading`

2021-09-22 10:14 UTC, antonmazhuto commented on src/ui/atoms/empty.tsx
>  };
fixed

2021-09-22 10:15 UTC, antonmazhuto commented on src/pages/card/view/page.tsx
> +  if (!card && !isLoading) {
done

2021-09-22 10:15 UTC, antonmazhuto commented on src/pages/card/view/page.tsx
> +    );
done

2021-09-29 10:27 UTC, azinit approved these changes

2021-10-03 18:54 UTC, sergeysova approved these changes

2021-10-03 18:54 UTC, merged