BOX-222/padaet-vkladka-users-pri-poiske
cardbox/frontend pull request #71
Opened 2021-09-29 08:27 UTC by antonmazhuto

### BOX-222/padaet-vkladka-users-pri-poiske
  
  - [ ] updated @effector/reflect

2021-09-29 10:25 UTC, azinit approved these changes

2021-10-03 18:50 UTC, sergeysova requested changes

2021-10-03 18:50 UTC, sergeysova commented on src/pages/card/view/model.ts
> +    return Boolean(viewer) && viewer?.id === card?.authorId;
```suggestion
    return viewer?.id === card?.authorId;
```

2021-10-03 18:50 UTC, sergeysova commented on yarn.lock
> +"@effector/reflect@^7.0.1":
В другом ПР уже обновили. Подтяни себе изменения пожалуйста

2021-10-03 19:05 UTC, closed without merging