BOX-94 BOX-237 Add ability to add/remove card to favorites
cardbox/frontend pull request #84
Opened 2021-10-28 19:47 UTC by antonmazhuto

2021-10-31 17:06 UTC, antonmazhuto commented on src/entities/card/model/index.ts
> +);
fixed

2021-10-31 17:06 UTC, antonmazhuto commented on src/entities/card/model/index.ts
> +
fixed

2021-10-31 17:06 UTC, antonmazhuto commented on src/entities/card/organisms/card-list.tsx
> +          isCardInFavorite={favoritesCards?.some((s) => s.id === card.id)}
fixed

2021-10-31 17:06 UTC, antonmazhuto commented on src/pages/home/model.ts
> +import { cardsListFx } from '@box/pages/user/model';
fixed

2021-10-31 17:07 UTC, antonmazhuto commented on src/pages/home/model.ts
> +);
done

2021-10-31 17:07 UTC, antonmazhuto commented on src/pages/home/page.tsx
> +
done

2021-10-31 17:07 UTC, antonmazhuto commented on src/pages/search/page.tsx
> +  );
done

2021-10-31 17:07 UTC, antonmazhuto commented on src/entities/card/organisms/card-list.tsx
> +  removeFromFavorites: (id: string) => void;
fixed

2021-10-31 17:07 UTC, antonmazhuto commented on src/pages/card/view/page.tsx
> +                isCardInFavorite={favoritesCards?.some((s) => s.id === card.id)}
done

2021-10-31 17:08 UTC, antonmazhuto commented on src/pages/card/view/page.tsx
> +  }, []);
решили что пока не критично и сделаю позже

2021-10-31 22:19 UTC, sergeysova requested changes

2021-10-31 22:19 UTC, sergeysova commented on src/entities/card/model/index.ts
> +  (ids, { cache }) => ids.map((id) => cache[id]),
У тебя может возникнуть ситуация, когда карточка в списке избранного ещё не попала в кеш. Тогда у тебя будет в сторе массив с `undefined`. И когда ты промаппишь массив в одно значение, то получишь пропуск обновления стора, либо падение в рантайме.

Решение 1: явно маппить в null. Тогда тайпскрипт подхватит тайпинги и ты сможешь промаппить значение в эффекторе и отловить неконсистентность

```suggestion
  (ids, { cache }) => ids.map((id) => cache[id] ?? null),
```

Решение 2: отфильтровать не найденное. Но тогда у тебя будет пустой массив, пока в кеше не появятся карточки, что не плохо, но иногда это не ожидаемое поведение

```suggestion
  (ids, { cache }) => ids.map((id) => cache[id]).filter(Boolean),
```

2021-10-31 22:19 UTC, sergeysova commented on src/entities/card/organisms/card-preview.tsx
> +  };
Эта логика должна быть в модели.
Здесь же только обработка клика по кнопке, всё остальное должна решать модель

2021-10-31 22:19 UTC, sergeysova commented on src/entities/card/organisms/card-preview.tsx
> +  }, []);
```suggestion
  const handleFavoritesAdd = useCallback((cardId: string) => addToFavorites(cardId), [addToFavorites]);
```

1. Лучше упрощать передачу данных из вью в модель насколько можно. Так будет проще жить. Лишний объект тут не нужен, если он не разъясняет что именно за строку мы передаем. Мб тут убрать `{ id }` или переименовать в `{ cardId }`?
2. В deps хуков надо передавать вызываемое событие, ведь реакт или эффектор может их пересоздать через `useEvent` из-за деталей реализации, а тут может отвалиться, ищи свищи потом. Лучше перестраховаться, благо это не сложн

2021-10-31 22:19 UTC, sergeysova commented on src/entities/card/organisms/card-preview.tsx
> +        <AddButton
Мне кажется имя `SaveCardButton` или `SaveButton` лучше отразит смысл.
Предлагаю поглядеть так: "кнопка добавить", что добавить? куда добавить?

2021-10-31 22:19 UTC, sergeysova commented on src/entities/card/organisms/card-preview.tsx
> +          isCardToDeckAdded={isCardInFavorites}
```suggestion
          isCardInDeck={isCardInFavorites}
```

```suggestion
          isCardInFavorites={isCardInFavorites}
```

```suggestion
          isCardSaved={isCardInFavorites}
```

2021-10-31 22:19 UTC, sergeysova commented on src/entities/card/organisms/card-preview.tsx
> +        icon={<IconDeckCheck title="Remove card from my deck" />}
Может вместо полного дублирования вынести под условие только иконку?

```tsx
const icon = isCardSaved
	? <IconDeckCheck title="Remove card from my deck" />
  : <IconDeckArrow title="Add card to my deck" />;
```

Иначе, кажется что в каждой строчке есть отличия и нужно внимательно просмотреть тело условия чтобы найти разницу, а когда разницу не видишь, начинаешь подозревать, что здесь что-то не очевидное.
Вынесением отличий в отдельные переменные может помочь, если отличия точечные.

2021-10-31 22:19 UTC, sergeysova commented on src/pages/card/view/page.tsx
> +              <CardPreview card={card} loading={isLoading} size="large" />
Кажется, что здесь loading лишний, так как все находится внутри условия `card && author`, а значит, пока карточки нет (`null`) этот кусок виден не будет

2021-10-31 22:19 UTC, sergeysova commented on src/pages/user/model.ts
>    (ids, { cache }) => ids.map((id) => cache[id]),
Та же тема с незаметченными айдишниками из кеша

2021-11-01 10:02 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +  };
Скажем так - это вообще должно лежать в фиче все как минимум)

2021-11-01 10:03 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +  };
Но для "быстрого запуска" оставили как есть

Хотя щас если не особо торопимся то да, желательно такое в модель вынести и в отдельную фичу раз на то пошло

2021-11-01 10:05 UTC, azinit commented on src/entities/card/organisms/card-preview.tsx
> +        icon={<IconDeckCheck title="Remove card from my deck" />}
Щас мб имеет смысл, но уже как минимум два отличающихся поля (icon и theme)

а до этого там кнопки значительней отличались, поэтому и сделано через такое ветвление 🤔

2021-11-01 10:06 UTC, azinit commented on src/pages/card/view/page.tsx
> +              <CardPreview card={card} loading={isLoading} size="large" />
@sergeysova Чет слишком много комментариев "out-of-scope", не?)

Антон же чисто "добавление/удаление избранного" реализовывал

2021-11-04 17:02 UTC, sergeysova approved these changes

2021-11-04 20:57 UTC, antonmazhuto commented on src/entities/card/model/index.ts
> +  (ids, { cache }) => ids.map((id) => cache[id]),
fixed

2021-11-04 20:58 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +        <AddButton
fixed

2021-11-04 20:58 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +          isCardToDeckAdded={isCardInFavorites}
fixed

2021-11-04 20:58 UTC, antonmazhuto commented on src/pages/user/model.ts
>    (ids, { cache }) => ids.map((id) => cache[id]),
fixed

2021-11-04 20:58 UTC, antonmazhuto commented on src/entities/card/organisms/card-preview.tsx
> +  }, []);
fixed

2021-11-10 17:12 UTC, merged